### ISSUE TITLE
Debian Stretch: syntax error in "debian/rules setup-debian"

### ISSUE THREAD

**Issue by v17564** [ungoogled-software/ungoogled-chromium-debian#118]
Hello. I find this error:

make: clang-10: No se encontró el programa

python3 -B debian/ungoogled-upstream/ungoogled-chromium/utils/patches.py merge -p debian/patches debian/ungoogled-upstream/ungoogled-chromium/patches
  File "debian/ungoogled-upstream/ungoogled-chromium/utils/patches.py", line 195
    f'--patch-bin "{args.patch_bin}" is not a command or path to executable.')

SyntaxError: invalid syntax
debian/rules:210: fallo en las instrucciones para el objetivo 'setup-debian'
make: *** [setup-debian] Error 1

**Comment by Eloston** [comment]
We don't support Stretch anymore, and we don't have any code in this repo that is compatible with Stretch. Debian also seemed to drop support for Stretch (latest version is 73), so I'd highly advise that you upgrade to Buster.

If you are okay with an old version of Chromium, I think the latest Stretch version we have is 72.0.3626.122-3.stretch1.
