### ISSUE TITLE
Debian Stretch: syntax error in "debian/rules setup-local-src"

### ISSUE THREAD

**Issue by v17564** [ungoogled-software/ungoogled-chromium-debian#119]
I find this error:

$ ./debian/rules setup-local-src
make: clang-10: No se encontró el programa
test -d ../download_cache || mkdir ../download_cache
python3 -B debian/ungoogled-upstream/ungoogled-chromium/utils/downloads.py retrieve -i debian/ungoogled-upstream/ungoogled-chromium/downloads.ini -c ../download_cache
INFO: Downloading "chromium" to "chromium-80.0.3987.162.tar.xz" ...
INFO: Downloading ../download_cache/chromium-80.0.3987.162.tar.xz ...
Progress: 100.0% of 796,961,972 B
INFO: Downloading hashes for "chromium"
INFO: Downloading ../download_cache/chromium-80.0.3987.162.tar.xz.hashes ...
Progress: 100.0% of 650 B
INFO: Verifying hashes for "chromium" ...
python3 -B debian/ungoogled-upstream/ungoogled-chromium/utils/downloads.py unpack -i debian/ungoogled-upstream/ungoogled-chromium/downloads.ini -c ../download_cache ./
INFO: Unpacking "chromium" to ./ ...

python3 -B debian/ungoogled-upstream/ungoogled-chromium/utils/prune_binaries.py ./ debian/ungoogled-upstream/ungoogled-chromium/pruning.list
./debian/scripts/remove_copyright_excluded
Traceback (most recent call last):
  File "./debian/scripts/remove_copyright_excluded", line 89, in <module>
    main()
  File "./debian/scripts/remove_copyright_excluded", line 55, in main
    _remove_files(map(Path, regular_paths))
  File "./debian/scripts/remove_copyright_excluded", line 38, in _remove_files
    shutil.rmtree(filepath)
  File "/usr/lib/python3.5/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)

TypeError: lstat: illegal type for path parameter
debian/rules:215: fallo en las instrucciones para el objetivo 'setup-local-src'
make: *** [setup-local-src] Error 1

**Comment by Eloston** [comment]
Closing for same reasons as #118.
