### ISSUE TITLE
git parameter error --recurse-submodules

### ISSUE THREAD

**Issue by v17564** [ungoogled-software/ungoogled-chromium-debian#120]
Hello. I use a MX Linux based on Debian 9 (Stretch) and my version of git is 2.11.0.

In the installation step:
git -C ungoogled-chromium-debian checkout **--recurse-submodules** TAG_OR_BRANCH_HERE

i need change for:
git -C ungoogled-chromium-debian checkout **-b** TAG_OR_BRANCH_HERE

**Comment by ghost** [comment]
We don't support Stretch anymore. The branch was deleted some time ago. I assume the other issues are also due to software being too old.

**Comment by ghost** [comment]
It appears newer releases of MX Linux are based on Debian 10. Is there some reason you can't just upgrade to that?

**Comment by v17564** [comment]
There are almost 1 reason: i use a program that isn't supported in new MX-19, easyMP3Gain.

And also need reinstall all, there isn't a direct upgrade from MX-18 to MX-19.

**Comment by ghost** [comment]
I see. The best I could find for a replacement are tools for setting replaygain such as bs1770gain which is in Debian 10.

**Comment by Eloston** [comment]
Closing for same reason as #118.
