### ISSUE TITLE
Build with Wayland Ozone Support

### ISSUE THREAD

**Issue by 4abab** [ungoogled-software/ungoogled-chromium-debian#146]
I would like to make a personal build with wayland ozone support so that I can remove x11/xorg packages from my system. What exactly do I need to change from the build instructions in README.md to do this?

**Edit: If anyone cares to work on this or research it then please report your results here. Thanks.**

**Comment by ghost** [comment]
We don't support that nor does the upstream packaging we're based on. @Eloston Is this something we would want to look into adding as some kind of optional flavor?

**Comment by Eloston** [comment]
I like the idea of supporting Wayland Ozone, but I don't know how we'd implement an "optional flavor". Should it be included as a configurable build flag somehow? A separate branch (maybe for `debian_sid` only, otherwise we'd have too many branches)? A separate repo?

**Comment by ghost** [comment]
If anyone cares to research this feature to know what we would have to do to support it then please do so. I don't have any interest in it but I am open to the possibility if it doesn't create a logistics nightmare. My main concern is that X11 and Wayland support are often mutually exclusive so it would likely require separate packages to work.

**Comment by jstkdng** [comment]
You just have to add these flags.
https://github.com/jstkdng/ungoogled-chromium-archlinux/blob/2b2d37399eeb50e40ef1574a73baddda13a17d67/PKGBUILD#L206
to enable ozone. You should probably add them to another branch.

**Comment by Eloston** [comment]
@jstkdng Is Ozone's support for Wayland and X11 mutually exclusive? What consequences do these flags have that would warrant a separate branch?

**Comment by jstkdng** [comment]
Right now you can build with use_ozone and use_x11 but you need some hacks to make it work. 

Quoting one of the devs:

> PS: Please note that this is a temp solution that will help to choose between ozone and non-ozone X11 build. The switch that will be used to choose the path is --enable-features=UseOzonePlatform. Once non-Ozone X11 path is removed (hopefully by Q1 2021 depending on how th finch trial goes), the wrapper will be removed. Please also note that it's impossible to build use_x11 && use_ozone without some hacks in PlatformCursor code. The changes to that are on their way to upstream.

Source of comment: https://chromium.googlesource.com/chromium/src.git/+/b19077327047f228468ed6ec29b7465aeeed130c

Until then, another branch should be used to avoid breaking stuff.

**Comment by Eloston** [comment]
I see, thanks for elaborating. In that case, I think @braewoods's point still stands; I don't think there's a good solution without creating a logistical nightmare. Even if we took the easiest route and added some flag to `debian/rules`, it'd create some hassle when merging changes from upstream.

Since Ozone will take over "soon", I think it makes more sense to wait for upstream to enable Wayland support. It also makes more sense based on Debian's philosophy.

**Comment by jstkdng** [comment]
Well, until that happens you could add something to the README to inform users on how to compile UC with ozone support.

**Comment by Eloston** [comment]
Either a patch in contrib or a page in [this repo's publicly-editable Wiki](https://github.com/ungoogled-software/ungoogled-chromium-debian/wiki) would be more appropriate places.

To anyone interested, feel free to contribute. For starters, I've added a short page about it here: https://github.com/ungoogled-software/ungoogled-chromium-debian/wiki/Wayland

**Comment by riyad** [comment]
FWIW I tried adapting the patches from Arch Linux linked above.
I managed to build 83.0.4103.116-1.focal3 on Ubuntu focal with the following patch:

```patch
diff --git a/debian/patches/archlinux/fix-vaapi-ozone-build.patch b/debian/patches/archlinux/fix-vaapi-ozone-build.patch
new file mode 100644
index 0000000..160c136
--- /dev/null
+++ b/debian/patches/archlinux/fix-vaapi-ozone-build.patch
@@ -0,0 +1,17 @@
+--- a/media/gpu/vaapi/BUILD.gn
++++ b/media/gpu/vaapi/BUILD.gn
+@@ -128,12 +128,12 @@ source_set("vaapi") {
+     ]
+   }
+
+-  if (ozone_platform_gbm || use_egl) {
++  if (ozone_platform_wayland || ozone_platform_gbm || use_egl) {
+     sources += [
+       "vaapi_picture_native_pixmap.cc",
+       "vaapi_picture_native_pixmap.h",
+     ]
+-    if (ozone_platform_gbm) {
++    if (ozone_platform_wayland || ozone_platform_gbm) {
+       sources += [
+         "vaapi_picture_native_pixmap_ozone.cc",
+         "vaapi_picture_native_pixmap_ozone.h",
diff --git a/debian/patches/archlinux/wayland-egl.patch b/debian/patches/archlinux/wayland-egl.patch
new file mode 100644
index 0000000..6e9209c
--- /dev/null
+++ b/debian/patches/archlinux/wayland-egl.patch
@@ -0,0 +1,22 @@
+--- a/ui/gl/gl_image_native_pixmap.cc 2020-05-18 11:40:06.000000000 -0700
++++ b/ui/gl/gl_image_native_pixmap.cc 2020-05-22 02:07:16.007770442 -0700
+@@ -288,6 +288,8 @@
+                                std::move(scoped_fd));
+   }
+ 
++  handle.planes[0].size = size_.GetArea();
++
+   return handle;
+ #endif  // !defined(OS_FUCHSIA)
+ }
+--- a/gpu/command_buffer/service/error_state.cc 2020-05-18 11:39:22.000000000 -0700
++++ b/gpu/command_buffer/service/error_state.cc 2020-05-22 13:43:09.181180388 -0700
+@@ -115,6 +115,8 @@
+     // buffer.
+     error = GL_NO_ERROR;
+   }
++  if (error == GL_INVALID_ENUM)
++    error = GL_NO_ERROR;
+   return error;
+ }
+ 
diff --git a/debian/patches/disable/buildbot.patch b/debian/patches/disable/buildbot.patch
index 5839115..d8614b2 100644
--- a/debian/patches/disable/buildbot.patch
+++ b/debian/patches/disable/buildbot.patch
@@ -157,3 +157,28 @@
    if (is_android) {
      use_raw_android_executable = true
    }
+--- a/ui/views/BUILD.gn
++++ b/ui/views/BUILD.gn
+@@ -1294,11 +1294,6 @@
+     }
+   }
+ 
+-  if (is_desktop_linux && use_ozone) {
+-    data_deps +=
+-        [ "//testing/buildbot/filters:linux_ozone_views_unittests_filters" ]
+-  }
+-
+   if (use_atk) {
+     sources +=
+         [ "accessibility/view_ax_platform_node_delegate_auralinux_unittest.cc" ]
+--- a/ui/ozone/BUILD.gn
++++ b/ui/ozone/BUILD.gn
+@@ -282,8 +282,6 @@
+   # Platform tests link ozone statically. Make sure we're not getting a
+   # 2nd copy of any code via the component.
+   assert_no_deps = [ "//ui/ozone" ]
+-
+-  data_deps = [ "//testing/buildbot/filters:ozone_unittests_filters" ]
+ }
+ 
+ # X11 backend has its own test suite only built when we are using the x11
diff --git a/debian/patches/series b/debian/patches/series
index d5cbde8..59cad68 100644
--- a/debian/patches/series
+++ b/debian/patches/series
@@ -143,6 +143,8 @@
 inox-patchset/fix-cfi-failures-with-unbundled-libxml.patch
 fedora/vaapi.patch
 fedora/vaapi-fix.patch
+archlinux/wayland-egl.patch
+archlinux/fix-vaapi-ozone-build.patch
 ungoogled-chromium/clang.patch
 ungoogled-chromium/icu66.patch
 ungoogled-chromium/manpage.patch
diff --git a/debian/rules b/debian/rules
index 03f36a8..c922dc0 100755
--- a/debian/rules
+++ b/debian/rules
@@ -67,7 +67,6 @@ defines+=$(shell cat debian/ungoogled-upstream/ungoogled-chromium/flags.gn | tr
 # disabled features
 defines+=is_debug=false \
          use_goma=false \
-         use_ozone=false \
          use_sysroot=false \
          use_openh264=false \
          use_allocator=\"tcmalloc\" \
@@ -108,6 +107,14 @@ defines+=use_gio=true \
          use_cups=true \
          use_kerberos=false \
          use_lld=true \
+         use_ozone=true \
+         ozone_platform_wayland=true \
+         ozone_platform_x11=true \
+         ozone_auto_platforms=false \
+         use_xkbcommon=true \
+         use_system_libwayland=true \
+         use_system_minigbm=true \
+         use_system_libdrm=true \
 
 # handle parallel build options
 njobs=1
```

**Comment by Eloston** [comment]
This isn't necessary anymore for recent Chromium. unportable already supports Wayland, and I'm running it now.
