### ISSUE TITLE
Update to Chromium 83

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#147]
It has landed in our upstream but upstream Debian has not yet updated. I intend to wait until then as we need to maintain history compatibility to a large degree with them. If anyone feels like trying to do this earlier then please do so but also please leave a comment in this issue if you are. I would just ask you make all patch updates in a single commit so we can easily revert it later when Debian finally does update.

**Comment by ghost** [comment]
First attempts at updating to 83 have landed in Debian upstream. But the resulting builds failed due to some ICU issue.

**Comment by ghost** [comment]
Another was uploaded and failed due to RE2 issues. Nothing in their VCS git yet.

**Comment by Eloston** [comment]
> Another was uploaded and failed due to RE2 issues. Nothing in their VCS git yet.

Is it perhaps related to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960361 ?

Also, are you updating Debian sid or buster?

**Comment by ghost** [comment]
I'm not doing either at the moment. I was tracking the progression of their work.
