### ISSUE TITLE
update to 83.0.4103.116-2

### ISSUE THREAD

**Issue by chaosmonk1** [ungoogled-software/ungoogled-chromium-debian#154]
83.0.4103.116-1 frequently crashes.  This is [fixed in  83.0.4103.116-2](https://tracker.debian.org/news/1156424/accepted-chromium-8304103116-2-source-into-unstable/).

**Comment by chaosmonk1** [comment]
Actually, I should have read more closely.  The crashes fixed in 83.0.4103.116-2 are caused by ffmpeg 4.3.  I'm experiencing crashes with ungoogled-chromium on Debian stable with ffmpeg 4.1, so I guess the crashes are unrelated.  Still would be good to update though.

**Comment by ghost** [comment]
I already know about this. It takes time for it to become available in their git.
