### ISSUE TITLE
Older releases of Ungoogled Chromium

### ISSUE THREAD

**Issue by ipeacocks** [ungoogled-software/ungoogled-chromium-debian#155]
Quite often latest Ungoogled Chromium get closed unexpectedly. It's hard to say why, nothing interesting in logs at first sight.
Is it possible to install previous version of Ungoogled Chromium somehow? I can't find previous release.

```
$ apt-cache madison ungoogled-chromium

ungoogled-chromium | 83.0.4103.116-1.focal1 | http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  Packages
```
Is it possible to leave at least few versions in official repository? Thanks.

**Comment by ghost** [comment]
It's actually not. It's a limitation most package managers have. They can only have one version of a given package name in a given repository. As for the crashes it's apparently a known upstream issue that we're waiting on a fix from.

**Comment by davidramiro** [comment]
Exactly, it's being [worked on ](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1753494.html) and affects exactly the same version as the latest release from the repo you linked.

Right now I am building `81.0.4044.138-1.buster1`. Hopefully that will temporarily fix the issue, if so I could share a Debian Buster amd64 binary when the build finishes, if that helps.

**Comment by davidramiro** [comment]
Alright, [here](https://kore.cc/deb/ungoogled-chromium_81.0.4044.138-1.buster1_amd64.zip) are the built packages of `81.0.4044.138-1.buster1`. Doesn't crash anymore, at least on two websites where it would crash every single time, 100% reproducible. Just as a temporary fix until upstream gets fixed.

**Comment by ghost** [comment]
Latest patches from upstream should now be out in the build. This is probably going to make a real difference for most.
