### ISSUE TITLE
build fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by the-good-stuff** [ungoogled-software/ungoogled-chromium-debian#168]
I followed the build instructions but the build fails. 
First I get some errors about missing files after I run ./debian/scripts/setup local-src 
[ungoogled_chromium1.txt](https://github.com/ungoogled-software/ungoogled-chromium-debian/files/4962676/ungoogled_chromium1.txt)

Then the build fails after dpkg-buildpackage -b -uc
[ungoogled_chromium2.txt](https://github.com/ungoogled-software/ungoogled-chromium-debian/files/4962678/ungoogled_chromium2.txt)

**Comment by ghost** [comment]
Part 1, totally normal. They're warnings.

Part 2, suggests missing dependencies. Did you forget to install something? You need to run the apt install and mk-build-deps prior to attempting any build setup.

**Comment by the-good-stuff** [comment]
I made a vm and seems to be working there. So then there's a problem on my side.

**Comment by the-good-stuff** [comment]
Aparently I should have waited until the end. The build still crashes.
To make sure I downloaded Ubuntu 20.04 iso, built a fresh VM, and followed the build instructions.
Now while building it crashes at some point.
Here's the output:
[error.txt](https://github.com/ungoogled-software/ungoogled-chromium-debian/files/4969976/error.txt)
Again, I followed your build instructions. If there are any other dependencies that I need they aren't in the build instructions from here: https://github.com/ungoogled-software/ungoogled-chromium-debian
I also tried resuming with dpkg-buildpackage -b -uc -nc , it starts again but fails the same soon. 
I also tried running dpkg-buildpackage -b -uc again and same thing.

**Comment by ghost** [comment]
I didn't catch this the first time but you're having issues because you're trying to build the sid branch against focal. You were supposed to do this with the git checkout command in the instructions. Check out the ubuntu_focal branch and try again.

**Comment by the-good-stuff** [comment]
That seems to have worked, it went past the failing point now. 
Switching to that branch still presents the same issues for my host machine but atm works in the VM.
Thank you for the help!
