### ISSUE TITLE
APNG flicker with APNG-patched libpng

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-debian#169]
I've been getting APNG flicker in Chromium for a little while. Warnings match those as discussed in https://bugs.chromium.org/p/chromium/issues/detail?id=752403#c10

Unfortunately, it seems [Debian also patches their libpng with APNG support](https://salsa.debian.org/debian/libpng1.6/-/blob/master/debian/patches/libpng-1.6.37-apng.patch).

The crbug [referenced an Arch issue](https://bugs.archlinux.org/task/55093), but there seems to be no solution to using Chromium with libpng patched with APNG support.

@braewoods Should we use the bundled libpng library instead?

**Comment by ghost** [comment]
I honestly never noticed as APNG doesn't have good adoption. Where do you go where this is a significant issue?

Edit: seems my information is old but I still rarely see APNG images.

**Comment by Eloston** [comment]
I also rarely encounter APNGs, but when the occur it's quite obvious. Off the top of my head, there are two places:

reddit.com uses them for animated post award icons (most likely you'll run into at least one on the frontpage)

parsecgaming.com uses it for the background of the main page, and several other animated images. The broken APNG animation causes the background to be black most of the time.

**Comment by ghost** [comment]
Which build are you having the issue with? I'm not seeing it with Bionic's build.

Edit: Evidently it's because Ubuntu Bionic doesn't patch PNG with APNG support. But Ubuntu Focal does.

**Comment by ghost** [comment]
I'll test this with Focal's build once I get around to upgrading in the near future so I can understand the issue better. But is this common enough for us to want to disable it?

**Comment by Eloston** [comment]
I am using 81.0.4044.138-1.buster1 (am using older version because https://github.com/Eloston/ungoogled-chromium/issues/1081 is blocking my upgrade).

> I'll test this with Focal's build once I get around to upgrading in the near future so I can understand the issue better. But is this common enough for us to want to disable it?

Given that APNG is somewhat adopted (also, reddit and parsecgaming are both modern sites, so they are probably not the only sites that use APNG) and that the rendering problems are pretty severe, I think it's worth fixing.
