### ISSUE TITLE
Video streaming not working in Microsoft Teams

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-debian#176]
I'm unable to share my webcam or stream my desktop in a Microsoft Teams meeting. This problem does NOT occur on Portable Linux or Windows, so I suspect there's a problematic Debian-specific setting.

Nothing was obvious to me on quick inspection of DevTools or standard output/error. I haven't investigated deeper yet.

Version: 84.0.4147.135-1.buster1

**Comment by ghost** [comment]
Could it be a distribution release specific issue? We should try it with the builds for Bionic and Focal. Do you have any instructions for how to test it?

**Comment by Eloston** [comment]
Bionic is also broken. I don't have the time to test Focal right now.

The easiest way to test Teams is to use any Microsoft Account to access Teams. Then you can create a link to a room that is accessible by non-Microsoft Account holders. I would share a link I use, but I'm don't want to accidentally expose any PII of the room creator.

**Comment by kabo** [comment]
Same issue in Slack. Not really sure how to troubleshoot it properly. I'm happy to assist in troubleshooting it (running stuff someone who knows more than I do tells me to run).

I just get this screen in Slack
![3kz32bjwy2k51](https://user-images.githubusercontent.com/357601/95668222-71dce500-0b60-11eb-8fb6-96417aabb514.png)

Teams just gives me a black screen.

Amazon Chime used to work until recently, but now it gives me screen similar to Slack's, but not exactly the same, the wording is different.

meet.jit.si works fine, as does whereby.com.

However, I've tested making a Slack call from user A on device A to user B on device B, and if both are running chromium (ungoogled or debian), video works! So yeah, just convince all your friends to run ungoogled chromium :D

**Comment by Eloston** [comment]
I suspect the root cause might be codec support. If video calling works between ungoogled-chromium and Debian chromium, perhaps it's a system ffmpeg issue? I'm not sure how to confirm this with an existing build.

EDIT: I noticed that both Portable and Arch Linux builds use `ffmpeg_branding="Chrome"` but Debian uses `ChromeOS`. A long time ago, `ChromeOS` was a strict superset of `Chrome`; I wonder if this is still the case?

**Comment by Eloston** [comment]
This should be solved in unportable.
