### ISSUE TITLE
Restarting Debian upstream development

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#184]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972134#37

A discussion is being held considering the establishment of a chromium packaging taskforce, with honorable mention of this project.

I am myself not a Debian developer or maintainer but I would keep an eye open and try to help according to my abilities, at least with testing.

**Comment by berkley4** [comment]
You're welcome to point the debian folks at my fork of this repo, where I've just finished updating to the latest release. It builds and seems to run fine.

The only thing I couldn't get working was widevine, disabled for now, but probably fixable.

[https://github.com/berkley4/ungoogled-chromium-debian/tree/87.0.4280.88](url)

Edit: I'm not sure why that url doesn't seem to work, try copying and pasting it. Everything is in the '87.0.4280.88' branch.

**Comment by Eloston** [comment]
Closing because upstream has restarted development. Let's consolidate discussion into #186.
