### ISSUE TITLE
Build failure for unportable

### ISSUE THREAD

**Issue by yl3dy** [ungoogled-software/ungoogled-chromium-debian#185]
Couldn't build "unportable" version following the instructions in the README: it fails when running `./debian/scripts/setup debian` with an error: `FileNotFoundError: [Errno 2] No such file or directory: '/home/user/ungoogled-chromium/build/src/ungoogled-chromium/chromium_version.txt'` (my root build dir is `/home/user/ungoogled-chromium`, cwd is `/home/user/ungoogled-chromium/build/src`).

My system is Ubuntu 18.04.

Also a minor issue in the building guide: `git switch unportable ; git submodule update --init` commands should use `-C` switch, and `switch` command is only available in newer git versions, maybe it should be replaced with `checkout` for better compatibility.

**Comment by ghost** [comment]
@yl3dy see https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/183#issuecomment-740870616
