### ISSUE TITLE
ungoogled-chromium depends on libre2-8 but it's not installable

### ISSUE THREAD

**Issue by HeteroChromia42** [ungoogled-software/ungoogled-chromium-debian#187]
Title. can we get this issue resolved? Running Debian Unstable.

**Comment by ghost** [comment]
@InspectorGilbert I've just built a fresh 87.0.4280.88-1.unportable1 and it depends on libre2-9. Perhaps if you would like to trust me and my build environment I could share the build.

**Comment by ghost** [comment]
if needed you can find libre2-8 at http://snapshot.debian.org/package/re2/20201001%2Bdfsg-1/

**Comment by okias** [comment]
@gadall please share build. Today I figured out there isn't possibility to install any Chromium (debian old pakcage doesn't encode video, flatpak chromium & ungoogled-chromium doesn't work due different sandboxing, ungoogled-chromium DEBs doesn't have all dependencies). Outch, I just wanted run M$ teams once.

EDIT: nevermind, I installed libre2 from snapshots and thankfully it's enough.
EDIT2: nope, it's version 84, so if you have 87, at least something..

**Comment by ghost** [comment]
@okias 

https://chromium.gedalya.net/chromium/

sha256:
```
52fd2ccd3a2998d611e340f7edf7f80437ca58fbe3d8a3a034808d780440c58e  ungoogled-chromium_87.0.4280.88-1.unportable1_amd64.deb
7ce25a9cbe75e2228103c1f3b48595863fdc984c79bc6b315c6f289cf37930fe  ungoogled-chromium-common_87.0.4280.88-1.unportable1_amd64.deb
3175d317279732230afd8e73c4272fe7d8a1f572049b534ebd72c12c44002344  ungoogled-chromium-common-dbgsym_87.0.4280.88-1.unportable1_amd64.deb
d1425d4ec94757a8019a5afe5ee37abc08ceb1fc6ce500627a00ce548cfe7e79  ungoogled-chromium-dbgsym_87.0.4280.88-1.unportable1_amd64.deb
9bad12000fda8e8e831e8feb4a6a45a704201a74aa6b3d3ad28aef9fd2b1fee4  ungoogled-chromium-driver_87.0.4280.88-1.unportable1_amd64.deb
e8713af4c0dd7300b84863d4fe2b4626a27137a5d209625739c2df2d88b342e5  ungoogled-chromium-driver-dbgsym_87.0.4280.88-1.unportable1_amd64.deb
f4c8222ee0fbad07260ed4581f6598f1c30861ab672123470a0fe0461fe88b7f  ungoogled-chromium-l10n_87.0.4280.88-1.unportable1_all.deb
e0a67eba6cc253c5f4582db9f05ac8d675c9ad50a15d345187d5b7c47285dc40  ungoogled-chromium-sandbox_87.0.4280.88-1.unportable1_amd64.deb
8b74b79e57eed3c8b889837fc8cf616190744f8c633fe67b68c699d4373cad92  ungoogled-chromium-sandbox-dbgsym_87.0.4280.88-1.unportable1_amd64.deb
```

**Comment by okias** [comment]
thanks @gadall u saved one M$ Teams meeting :D

**Comment by Eloston** [comment]
Closing because issue is resolved and old.

For reference, I build unportable on Debian stable, so that's why you're having dependency issues on testing, sid, and experimental. Technically there shouldn't be any dependency on libre, but the Debian packaging metadata needs to be updated (#188).
