### ISSUE TITLE
Readme instruction refers to nonexistent directory; cannot proceed with build

### ISSUE THREAD

**Issue by PrecisionWordcraft** [ungoogled-software/ungoogled-chromium-debian#189]
This line in the readme refers to a nonexistent directory:

cp -r ungoogled-chromium-debian/debian build/src/

Without the correct instruction here you can't proceed with a build.

**Comment by Eloston** [comment]
**If you're not looking at the `unportable` branch**, the instructions in that README should be correct. Which directory is missing?

**If you're looking at the `unportable` branch**, the `build` directory now lives at the root of the git repo (it is ignored by `.gitignore`).

Make sure you're following the README instructions in the branch you're building. Let me know if you have further issues.
