### ISSUE TITLE
Depends: libre2-8 on Debian Sid issue

### ISSUE THREAD

**Issue by lf94** [ungoogled-software/ungoogled-chromium-debian#191]
The sid package requires libre2-8 but only libre2-9 exists. Installing libre2-9 does not resolve the conflict. Updating the control file should resolve the issue!

**Comment by lf94** [comment]
I was able to continue installation by installing the missing package from here: https://snapshot.debian.org/binary/libre2-8/

**Comment by SugaryHull** [comment]
@lf94 This is a [known issue](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/187) with building on Debian Sid, as this repo tends to target Debian Stable. More information can also be found [here](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/188).

**Comment by ghost** [comment]
This is probably due to how old the existing OBS builds are. I'm still waiting for chromium 88 to land in our upstream so it should be dealt with then.

**Comment by ghost** [comment]
This will be fixed soon when the new debian sid builds are available in this next week or so. This is no longer relevant.
