### ISSUE TITLE
Cannot install due to unmet dependencies, Ubuntu 20.04.1

### ISSUE THREAD

**Issue by ronaldl29** [ungoogled-software/ungoogled-chromium-debian#193]
I am following the Ubuntu install instructions and receiving this error:

` ungoogled-chromium : Depends: libavcodec57 (>= 7:3.4.8) but it is not installable or
                               libavcodec-extra57 (>= 7:3.4.8) but it is not installable
                      Depends: libavformat57 (>= 7:3.4.8) but it is not installable
                      Depends: libavutil55 (>= 7:3.4.8) but it is not installable
                      Depends: libevent-2.1-6 (>= 2.1.8-stable) but it is not installable
                      Depends: libre2-4 (>= 20160901) but it is not installable
                      Depends: libvpx5 (>= 1.6.0) but it is not installable
                      Recommends: ungoogled-chromium-sandbox but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
`

**Comment by SugaryHull** [comment]
@ronaldlong46 My guess would be that these dependencies were updated in Ubuntu in a way that broke these older OBS builds of ungoogled-chromium. Try my build of [ungoogled-chromium 87.0.4280.141-1.unportable](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/debian_unportable/87.0.4280.141-1.unportable1) and see if you have the same issues. I have personally only tested it in Debian Buster, but it was deemed stable enough to merge, so it may very well work on Ubuntu Focal.

**Comment by ghost** [comment]
This will be resolved when I get around to working on Focal.
