### ISSUE TITLE
Temporarily replace OBS install instructions with a link to https://ungoogled-software.github.io/ungoogled-chromium-binaries/

### ISSUE THREAD

**Issue by SugaryHull** [ungoogled-software/ungoogled-chromium-debian#195]
It seems that the OBS builds for Ubuntu Focal [no longer install correctly](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/193), so it might be advisable to temporarily point people to the community-contributed builds of ungoogled-chromium until OBS can be resumed along with Debian upstream. Additionally, [Ubuntu has also switched to using a Snap to install Chromium](https://snapcraft.io/blog/chromium-in-ubuntu-deb-to-snap-transition), which may present issues for using OBS to build for Ubuntu.

**Comment by Eloston** [comment]
Pinning for more visibility to users.

@braewoods Do you have a rough ETA of when we can update with changes from upstream? If it's soon, we may not need to update the README.

**Comment by ghost** [comment]
@Eloston I'm working on it now. See the draft PR.

**Comment by grandtoubab** [comment]
Hi folks,
Here is the way I use it
https://bidouilledebian.wordpress.com/2021/01/18/de-google-iser-son-navigateur/

What do you think of that?
