### ISSUE TITLE
Request to reintroduce Unportable

### ISSUE THREAD

**Issue by TheJags** [ungoogled-software/ungoogled-chromium-debian#211]
Going through issues, came across following 2 comments:

(1) "I [never managed to get it building](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/197#issuecomment-803606822) so i never tagged it."

(2) "... so I probably won't update unportable [unless I find a good reason to](https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/183#issuecomment-774628849)."

@Eloston is it possible/feasible for you to reintroduce **[Unportable](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/debian_unportable/amd64/)** so that Ubuntu 20.04, 20.10, and 21.04 can have latest Ungoogled Chromium ?

Many thanks.

**Comment by ghost** [comment]
@TheJags I haven't given up yet. I'm still working on it but I got stalled last time so it didn't work out for 88. I should be done with Debian for 89 soon assuming Buster builds.

**Comment by TheJags** [comment]
> @TheJags I haven't given up yet. I'm still working on it but I got stalled last time so it didn't work out for 88. I should be done with Debian for 89 soon assuming Buster builds.

@braewoods thank you so much :)
