### ISSUE TITLE
Ubuntu binary stale compared to Debian

### ISSUE THREAD

**Issue by dkebler** [ungoogled-software/ungoogled-chromium-debian#213]
Any reason why the stable Ubuntu focal binary is not rebuilt when buster/sid is?  buster/sid corresponds to latest release tag ( a few days ago), but the focal binary is still a binary from a release tag 7 months ago.

https://build.opensuse.org/project/show/home:ungoogled_chromium

even in the dev branch the focal binary is one month behind.
https://build.opensuse.org/project/show/home:ungoogled_chromium

**Comment by dkebler** [comment]
BTW -  really really appreciate this project.  If there is a way I can help keep ubuntu binary current to releases let me know.

**Comment by Joffreybvn** [comment]
I tried to build it on Focal, but I got an error related to "VPX". Currently, resolving this bug is beyond my comprehension.
However, I think @braewoods is investigating this issue.

I'm also open to help if needed !

**Comment by dkebler** [comment]
If @braewoods doesn't solve it soon I'll try building it myself (I run mint 20/focal on my dev box)

**Comment by dkebler** [comment]
one question.   Do you know why the dev branch built ok for that release a month ago but the stable branch (which apparently has the same release at this point) did not?
