### ISSUE TITLE
APT only sees armhf packages in OBS on amd64

### ISSUE THREAD

**Issue by unilock** [ungoogled-software/ungoogled-chromium-debian#222]
Hi all.

I'm running Pop!_OS 20.10 on an amd64 machine.

When following the instructions [here](https://github.com/ungoogled-software/ungoogled-chromium-debian#installing) (for Ubuntu Focal, also tried instructions for Debian Sid) to add the OBS repository, and running `apt search ungoogled-chromium`, the relevant packages are listed as only supporting the armhf architecture (except `ungoogled-chromium-l10n`, as expected).

I have not yet tried adding the Development repo, rather than the Stable repo, but have no reason to believe that would behave any differently (then again, computers are strange).

`lsb_release`:
```
Distributor ID: Pop
Description: Pop!_OS 20.10
Release: 20.10
Codename: groovy
```

`uname -a`:
```
Linux optiplex 5.8.0-7642-generic #47~1614007149~20.10~82fb226-Ubuntu SMP Tue Feb 23 02:59:01 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ghost** [comment]
We don't support 20.10 or any of its derivatives. I'm not sure what made you think we did. We will be supporting the next release but the previous one was skipped due to some upstream issues.
