### ISSUE TITLE
What to do with build output?

### ISSUE THREAD

**Issue by rwjack** [ungoogled-software/ungoogled-chromium-debian#227]
Quite a noob question,

Since I noticed no one wants to build the latest version for debian I decided I'd pitch in, but it seems I have no clue what to do with the output.

It's bad enough that the entire build crashed because I didn't have a GPG key for signing, so I had to re-do the entire thing. Now I'm, stuck with the following:

```
drwxr-xr-x    - abc 29 Apr 12:17 download_cache
drwxr-xr-x    - abc 29 Apr 14:23 src
.rw-r--r-- 663k abc 29 Apr 14:23 ungoogled-chromium_90.0.4430.85-1.sid1.debian.tar.xz
.rw-r--r-- 3.6k abc 29 Apr 14:51 ungoogled-chromium_90.0.4430.85-1.sid1.dsc
.rw-r--r-- 242k abc 29 Apr 14:51 ungoogled-chromium_90.0.4430.85-1.sid1_source.build
.rw-r--r--  23k abc 29 Apr 14:51 ungoogled-chromium_90.0.4430.85-1.sid1_source.buildinfo
.rw-r--r-- 2.4k abc 29 Apr 14:51 ungoogled-chromium_90.0.4430.85-1.sid1_source.changes
.rw-r--r-- 403M abc 29 Apr 12:32 ungoogled-chromium_90.0.4430.85.orig.tar.xz
```

Followed [this](https://github.com/ungoogled-software/ungoogled-chromium-debian#building-via-source-package) guide.

Wat do?

Also, I've tried building the Appimage for the linux unversal version, but got a whole bunch of errors,
`error: use of undeclared identifier 'VP9E_SET_DELTA_Q_UV`,
this one was the dealbreaker.

**Comment by ghost** [comment]
You built a source package which is only suitable if you're planning to upload to something like Launchpad or OBS. You should just build a normal binary package and ignore the package signing failure. It only really matters if you plan to upload to an APT repository.
