### ISSUE TITLE
Ungoogled chromium 84 for Ubuntu 18.04/Linux Mint 19.3?

### ISSUE THREAD

**Issue by Aufschlauer** [ungoogled-software/ungoogled-chromium-debian#230]
Hi,

I'm trying to understand how the latest binary of Ungoogled Chromium for Ubuntu 18.04/Linux Mint 19.3 was build. Actually which tag was used?

For version 84 I can only find tags for

- sid
- hirsute
- focal
- buster

In case I would rebuild the 84 release for Ubuntu 18.04/Linux Mint 19.3: Which tag I've to use?

Thx!

**Comment by ghost** [comment]
None. We dropped support for Bionic due to the increasing difficulty of building it. You can upgrade to Linux Mint 20.x and use Focal instead.
