### ISSUE TITLE
Fonts Not Showing Up in Light Websites on Hirsute Hippo

### ISSUE THREAD

**Issue by JosephReza** [ungoogled-software/ungoogled-chromium-debian#231]
Hello,

I am using Kubuntu 21.04 on this 81X2 IdeaPad Flex 5 14ARE05 with an AMD Ryzen 7 4700U with Radeon Graphics (8) @ 2.000GHz for the CPU and an AMD ATI 04:00.0 Renoir for the GPU (integrated graphics). The UC version is Chromium 90.0.4430.93 built on Ubuntu hirsute/21.04, running on Ubuntu hirsute/21.04. 

When I go on certain websites - such as Github and Google - I have an issue where the font does not display at all. This did not happen on the latest Flatpak version nor did it happen in Brave, which leads me to believe that this is an issue with this specific build of Chromium.

Examples: https://cdn.discordapp.com/attachments/743875436915982347/840352611643293707/unknown.png 
https://cdn.discordapp.com/attachments/743875436915982347/840352729134137354/unknown.png

I tried changing fonts and turning off hardware acceleration while clearing the cache and neither worked.

**Comment by TheJags** [comment]
I too am having exact same issue on Ubuntu MATE 21.04 Hirsute.

In addition, when I enabled the repo for Hisute:

````
echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Hirsute/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium.list
curl -fsSL https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Hirsute/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_ungoogled_chromium.gpg > /dev/null
sudo apt update
````
I get these `armhf` packages in `Synaptic`. Yesterday they were being displayed as `arm64` but after I ran `sudo apt update`, today it changed somehow:
![ungoogled_packages](https://user-images.githubusercontent.com/47936415/117546242-123baf00-b047-11eb-9c6f-340b209add01.jpg)

So I installed `Ungoogled Chromium` by directly downloading:
`
https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Hirsute/amd64/ungoogled-chromium_90.0.4430.93-1.hirsute1_**amd64.deb**
`

Thanks.

**Comment by ghost** [comment]
The new build has a patch that addresses a similar problem with Arch's chromium packaging. Let me know if this is still an issue.

**Comment by TheJags** [comment]
@braewoods by new build, did you mean `90.0.4430.93-1.hirsute1`?

Because I cleared apt package lists, clean, autoclean, autoremove, and then run apt update... but still Synaptic only offers ungoogled packages for `armhf` architecture (as I've mentioned in my previous post) on `amd64` desktop pc.

![uc_armhf](https://user-images.githubusercontent.com/47936415/118313921-0ea99b80-b511-11eb-9c2a-91a2dbbf7c08.jpg)

is something wrong with OBS ?

This is how I've added the repo for Hirsute:
````
echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Hirsute/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium.list
curl -fsSL https://download.opensuse.org/repositories/home:ungoogled_chromium/Ubuntu_Hirsute/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_ungoogled_chromium.gpg > /dev/null
sudo apt update
````
Many thanks.

**Comment by ghost** [comment]
It hasn't finished building yet. Patience. That was just when I pushed it out.

**Comment by JosephReza** [comment]
Just updated now and it works, thank you very much!

I'll leave this open for you to close in case anyone else sitll has an issue with this still.

**Comment by TheJags** [comment]
> It hasn't finished building yet. Patience. That was just when I pushed it out.

Okay. Just installed version `90.0.4430.212-1.hirsute1` and it's working just fine.

Thank you.
