### ISSUE TITLE
Please... Please give me Ubuntu_Bionic ungoogled-chromium

### ISSUE THREAD

**Issue by tomoyukikino** [ungoogled-software/ungoogled-chromium-debian#232]
I want to install in another ubuntu18.04(Bionic) machine. but I cant.

because, Ubuntu_Bionic version is discontinued.
https://github.com/ungoogled-software/ungoogled-chromium-debian/commit/ebbe8aed9aa2568225f2dd4aad74df9c5a27da69

please... please give me  Ubuntu_Bionic ungoogled-chromium..
please😭😭😭😭

**Comment by ghost** [comment]
18.04 is already discontinued on most of the flavors and I removed it because it was proving far too difficult to keep it building. 20.04 has already replaced it for the most part so I suggest you upgrade to it or a derivative based on it instead.

**Comment by tomoyukikino** [comment]
@braewoods 
okey, thanks. I do upgrarde.
