### ISSUE TITLE
Unavailable as default application in Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by steefzilla** [ungoogled-software/ungoogled-chromium-debian#236]
![image](https://user-images.githubusercontent.com/2222023/127481473-04b0ac30-4132-42f4-b64c-33f6c1dde85c.png)

Ungoogled Chromium is unavailable to select as the default application for web links in gnome-control center.

![image](https://user-images.githubusercontent.com/2222023/127481392-dbf806a7-b935-4f99-a323-9c86ddf64c0f.png)

![image](https://user-images.githubusercontent.com/2222023/127481637-58a0e280-d592-4054-b77d-f71acb760a35.png)

**Comment by ghost** [comment]
Sounds like a desktop file issue. Will investigate further once current upgrade is done.

**Comment by ghost** [comment]
This appears to be fixed on latest release.
