### ISSUE TITLE
No video codecs supported (webrtc_video_engine.cc)

### ISSUE THREAD

**Issue by SvenSemmler** [ungoogled-software/ungoogled-chromium-debian#237]
Running Version 90.0.4430.212 (Developer Build, ungoogled-chromium) built on Debian buster/10, running on Debian buster/10 (64-bit) from http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Buster/

Use Case: WebEx conference; enable WebCam; see WebCam output locally but remote participants do not see video

Console output:

[1164:17:0802/170034.483429:ERROR:webrtc_video_engine.cc(814)] No video codecs supported.
[1164:17:0802/170034.483966:ERROR:sdp_offer_answer.cc(4264)] Failed to set remote video description send parameters for m-section with mid='0'. (INVALID_PARAMETER)
[1164:17:0802/170034.484444:ERROR:sdp_offer_answer.cc(2204)] Failed to set remote answer sdp: Failed to set remote video description send parameters for m-section with mid='0'.

Looking at the code I see this:

  // We should only fail here if send direction is enabled.
  if (params.is_stream_active && negotiated_codecs.empty()) {
    RTC_LOG(LS_ERROR) << "No video codecs supported.";
    return false;
  }

Is WebRTC in general or sending video specifically disabled in this build? Or am I missing some packagages ungoogled-chromium depends on (running on debian-10-minimal / Qubes OS).

I'd like to get this working with ungoogled-chromium. If I have to build myself, that's fine. But I could use a pointer or two figuring out what causes this in the first place.

**Comment by yyyjajp** [comment]
Perhaps related to
https://stackoverflow.com/a/48326215

**Comment by eLvErDe** [comment]
Hello,

I'm indeed pretty sure it's related to missing Cisco OpenH264, would you like me to provided a built to confirm this is the issue ?

Regards, Adam.

**Comment by SvenSemmler** [comment]
On 9/29/21 01:01, Adam Cécile wrote:
> I'm indeed pretty sure it's related to missing Cisco OpenH264, would you like me to provided a built to confirm this is the issue ?

If that's an easy thing for you to do: yes.

Thank you!

-- 
  public key: https://www.svensemmler.org/2A632C537D744BC7.asc
fingerprint: DA59 75C9 ABC4 0C83 3B2F 620B 2A63 2C53 7D74 4BC7

**Comment by eLvErDe** [comment]
@SvenSemmler 

Here you go: https://cloud.le-vert.net/s/RXxNGxCxEvvX0fN

**Comment by SvenSemmler** [comment]
I will try later today and let you know. Thank you!


-- 
  public key: https://www.svensemmler.org/2A632C537D744BC7.asc
fingerprint: DA59 75C9 ABC4 0C83 3B2F 620B 2A63 2C53 7D74 4BC7

**Comment by SvenSemmler** [comment]
@eLvErDe thank you again, I can confirm that your build works and I no longer see the issue.

**Comment by eLvErDe** [comment]
Great.

I do think it's a real issue, I opened a jug at debian but got no reply...
This could be fixed on ungoogled chromium...

@braewoods whats your opinion about this ? I can provide a packaging patch to reintroduce h264 support

**Comment by ghost** [comment]
@eLvErDe This is the kind of thing @Eloston would need to approve. I believe h264 is disabled for some licensing reason. The regular chromium also has it disabled from what I was reading.

**Comment by eLvErDe** [comment]
I successfully built debian 11 package with h264 enabled, are you interested in @SvenSemmler 

@braewoods would you consider re-opening this ticket ? In my opinion that's a quite severe issue, all debian-ecosystem chromium are shipped *without* h264 WebRTC support and this discussion has to be brought back on top...

**Comment by Eloston** [comment]
@braewoods We have enabled proprietary codecs here: https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/ff59a86d08b40f3847d9f694d897989f472cd799/debian/rules#L102-L103
This includes H264, but this is applicable to regular video playback. For WebRTC, it seems there is another flag that is set to false here: https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/ff59a86d08b40f3847d9f694d897989f472cd799/debian/patches/disable/openh264.patch#L12
It should be fine to remove this patch since we've been building with proprietary codecs for a while now. We'd also need to remove these lines:
https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/ff59a86d08b40f3847d9f694d897989f472cd799/debian/copyright#L114-L115
https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/ff59a86d08b40f3847d9f694d897989f472cd799/debian/clean#L20
