### ISSUE TITLE
Debian Testing (Installation Instructions)

### ISSUE THREAD

**Issue by mekeor** [ungoogled-software/ungoogled-chromium-debian#238]
- Debian version 11, called _Bullseye,_ has been released on August 14th, 2021. The testing release now called _Bookworm_.
- The README of this repository only holds installation instructions for _Buster_ (Debian 10) and _Sid_ (unstable).
- I.e. it seems that there were only installation instructions for the stable and for the unstable release – before Debian 11 had been released.
- How to install ungoogle-chromium on Debian testing: Bookworm? Could we elaborate on that in the README?

**Comment by ghost** [comment]
Testing is close enough to Sid in general that we do not bother trying to support testing. Use Sid if you're wanting that.

**Comment by swarupbhc** [comment]
@braewoods I was trying to install on debian testing, but it's giving me this error.

![image](https://user-images.githubusercontent.com/55395995/153036015-fea5f2d6-653b-4c37-80e3-2519192c77bc.png)
