### ISSUE TITLE
How does ungoogled chromium differ from debian chromium?

### ISSUE THREAD

**Issue by ilu33** [ungoogled-software/ungoogled-chromium-debian#24]
Would it be possible to explain this in the Wiki? Does it differ at all? Is there a reason to prefer one over the other? Do you collaborate?

**Comment by Eloston** [comment]
Good question, I'll add a section to the README.

**Comment by ilu33** [comment]
@Eloston Thank you for not adhering to that weird debian decision to eliminate lighthouse/tracing. I'm glad I finally found a chromium version I can work with - without ignoring those in need of accessibility features. You should explicitly point out that difference in the readme because Audits are an important feature for web developers.

Edit: Background for anybody who hasn't seen this: https://github.com/GoogleChrome/lighthouse/issues/7246

**Comment by zrose584** [comment]
@ilu33 
ehm.. what version of ungoogled-chromium are you talking about?
AFAIK the patch [debian/disable/tracing.patch](https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/debian_buster/debian/patches/disable/tracing.patch) is still applied.
Just checked, about://tracing does not work for ungoogled-chromium_76.0.3809.132-1.buster1_amd64.deb

I was thinking about removing it on my OBS v78 build though..

Maybe you are using ubuntu?

**Comment by ilu33** [comment]
I just downloaded v. 77.0.3865.120, installed on debian 10, used the readme, and audits work. I'm not getting the tracing/lighthouse errors I'm getting on the deb10 repository build. The about://tracing output looks ok.

Actually I've seen that patch too but I'm not complaining ... :-)

Although I usually agree with debian I cannot understand the debian decision on this issue - they don't claim that the third party js libraries are not open source and free, they just complain that it's minified. debian chromium packaging seems to be stuck anyway. 

Please keep audits working - web development for handicapped people really needs this functionality and it's hard to find a portable chromium build anywhere else. 

**Edit:**  My bad, I downloaded the generic linux portable version because it was newer! I edited to remove my mistake. Anyway, if anybody with the tracing problem sees this, they know which way to go!(It could still be somehow mentioned in one of the readme's.)
