### ISSUE TITLE
Debian GNU/Linux 10 - apt repo showing error while apt update

### ISSUE THREAD

**Issue by debuggerboy** [ungoogled-software/ungoogled-chromium-debian#240]
Hello,

I am using Debian GNU/Linux 10, I haven't yet upgraded to Debian GNU/Linux 11.

I am trying to do a `sudo apt get update` and I am getting below error.

```
Reading package lists... Done
E: The repository 'http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Buster  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

When I check : `http://download.opensuse.org/repositories/home:/ungoogled_chromium/` I do not see a `Debian_Buster` directory.

[Imgur](https://imgur.com/hhVwQjM)

what might be causing this issue?

Thanks,
Anish

**Comment by ghost** [comment]
Support for Buster has been removed since the upstream we are derived from is no longer supporting it. I suggest updating to Bullseye once it is ready.

**Comment by nestukh** [comment]
I'm having the same problem, but it's ok.
I'd like to add to the conversation that personally I wait to upgrade to last stable Debian until November or holiday season in December, usually for critical bugs being addressed after the initial release, new Firefox ESR later in October, downtime opportunity, and the peace of mind for fixing new bugs (you know how it works, old problems get resolved but new ones are introduced, it's life).
Sometimes I don't upgrade packages right away so I could miss the latest ones.
My suggestion for the next time, when Debian Bookworm will be Stable, is to leave the repo there few more months, with the last build you can make for Bullseye, even if it isn't the lastest update. That's ok, libraries and dependencies change and it's harder to backport. It's more than understandable.
Anyway, thanks for the porting, normal Chrome/Chromium are so unstable in comparison! Have a nice day.
