### ISSUE TITLE
Separation from Debian upstream and unification of branches

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#241]
I've given it thought for sometime now and I think I've decided how I am going to solve the issue with our builds becoming outdated. The issue has always been due to delays with Debian upstream. I cannot expect this situation will correct itself anytime soon so I think our only option is to separate ourselves and maintain our own packaging.

On that note I also think it would be most productive to target our efforts towards the lowest common denominator, the oldest distribution release we support. It will allow us to unify our packaging so one set of files will produce builds for all supported releases. This will also mean shedding patches for system libraries that are most prone to breaking with Chromium releases since most of the distribution releases won't have a new enough library to work without heavy patching if at all.

Both of these changes should allow us to reach similar parity to the Fedora and Arch packaging repositories so we have less baggage and fewer hackjobs overall not to mention being able to respond to our own upstream releases more quickly. This should allow our packages to be a suitable daily driver for most users. It involves some compromises but it should achieve results. I will begin work on it once I am in a position to do so.

**Comment by Amr-Ibra** [comment]
Could you please think about helping maintain the Debian package upstream instead of maintaining a separate downstream packaging?
https://tracker.debian.org/pkg/chromium
You don't have to be a Debian developer for it.

The packaging is here:
https://salsa.debian.org/chromium-team/chromium

Maybe @mimi89999 could help with that. He is the last uploader in Debian unstable.

**Comment by ghost** [comment]
@Amr-Ibra I have been doing this for over a year. Debian upstream has been a recurring source of frustration from the lack of regular updates. I often end up undoing things they do upstream because they are not compatible with our requirements, namely that we're trying to support multiple semi-compatible releases and Debian only cares about their own releases.

That and I don't particularly care to deal with the red tape that is involved in adhering to Debian packaging policy. Packaging chromium is enough of a hassle as it stands.

**Comment by Eloston** [comment]
I agree with all your points @braewoods, and it is essentially the reason why I created unportable a while back. We should consider reviving it and build it against the oldest Debian distro we want to support.

While we make unportable the default branch, we could keep the other branches around if someone comes along and is interested in maintaining a version that is closer to Debian's packaging (can be useful if we want to be included in Debian someday).

**Comment by Eloston** [comment]
Another point we can consider in a separate discussion is what exactly we want to include in the lowest common denominator build. Do we want no system integrations just like the upstream Portable Linux build? Enabling keyring support? How about VA-API (I personally use this)?

**Comment by ghost** [comment]
I would prefer to link to system libraries only when they are stable enough to not require constant patching to keep up with upstream Chromium changes. This means we would no longer be using system ICU at the very least.

**Comment by ghost** [comment]
In essence I would like to achieve a package that doesn't get heavily patched beyond our UC patchset so we can have a package that is truer to what we envision UC to be.

**Comment by Eloston** [comment]
Sure, makes sense to me. Keyring support is a feature that doesn't require any patching. VA-API requires some patching, but usually I grab those patches from Arch Linux since their packaging updates quickly. I agree that we should avoid creating any patches of our own.

**Comment by ghost** [comment]
I've started work on a new set of packaging files that I am building from the ground up to break away from most of the legacy baggage in the existing set. My goal is going to be having a single branch supporting all our current release targets and minimize any release specific bits. That should greatly help as if it can be made to compile on the oldest supported release it should work just fine on the newer ones as well.

**Comment by ghost** [comment]
I got this idea from seeing how Fedora packaging is able to do this with a single set of packaging files for all the Fedora related releases and some CentOS ones as well.

**Comment by ghost** [comment]
This is now complete. I have setup the new unified packaging set. @Eloston please review the new stuff and change what else you think it needs. I've done as best as I can but it should be much easier to maintain for future upgrades.
