### ISSUE TITLE
[bullseye] Local building is broken

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-debian#242]
Due to d64319321e77f43823f102d12fb58b926871407e, the build instructions no longer work: https://github.com/ungoogled-software/ungoogled-chromium-debian/tree/debian_bullseye#building

We need some way to download these external dependencies that is independent of the OBS workflow

**Comment by ghost** [comment]
The issue is that the bullseye typescript package doesn't work with Chromium 93. I'm not sure why exactly but including a new typescript distribution solved the issue.

**Comment by ghost** [comment]
This is no longer busted with the new packaging.
