### ISSUE TITLE
Help needed, how to rebuild without clean

### ISSUE THREAD

**Issue by backlux** [ungoogled-software/ungoogled-chromium-debian#244]
Hello, I'm new to debian. Already built the package. But I need to modify part of the code, after make changes.

dpkg-buildpackage -b -uc -nc won't rebuild changed source codes.

Any idea how to modify the debian/rules or how to config dpkg-buildpackage  to rebuild part without clean. 

Thanks for your help!

**Comment by ghost** [comment]
Normally this is done by introducing the change as a patch and adding it to the series file. Please clone a fresh repository and try again. I have updated the packaging with a whole new set.
