### ISSUE TITLE
No hash entry in release file in the open suse repo

### ISSUE THREAD

**Issue by sourav-majumdar-math** [ungoogled-software/ungoogled-chromium-debian#246]
I use the open suse repo to get ungoogled-chromium on Ubuntu 20.04. I get the following error

```
W: No Hash entry in Release file /var/lib/apt/lists/partial/download.opensuse.org_repositories_home:_ungoogled%5fchromium_Ubuntu%5fFocal_InRelease
E: The repository 'http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  InRelease' provides only weak security information.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by ghost** [comment]
I'm aware. I'm currently working on the new packaging to make Chromium 94 available.

**Comment by ghost** [comment]
Ok. It should be available for all but Impish once the builds finish. Impish is having issues on OBS that I am going to wait a bit longer on to investigate as I suspect they are temporary issues due to the recent addition of Impish to OBS.

**Comment by sourav-majumdar-math** [comment]
Thanks for looking into it. I am on Focal and I continue to get the same error message

**Comment by brainchild0** [comment]
For me, this issue has been resolved, since about several hours before my writing this comment.

**Comment by sourav-majumdar-math** [comment]
It is resolved for me too, I guess I should close the issue with this.
