### ISSUE TITLE
[unified] Severe usability issues on the unified build

### ISSUE THREAD

**Issue by markozajc** [ungoogled-software/ungoogled-chromium-debian#247]
For the past hour I've been trying to get my extensions to work on UGC 94.0.4606.81 to work on Debian Bookworm. So far I've bumped into:
- Webpages not loading at all unless HTTPs and uBlock Origin are disabled
- uMatrix broke completely, reinstalling it fixed it, but it hangs and goes back to the broken state whenever I try to restore the settings. If I apply rules little by little (I have about 4k of them), it hangs on about 2k and doesn't take any more.
- KeePassXC-Browser randomly not connecting to the database
- 'Load unpacked' in chrome://extensions randomly not working

None of these issues have been present in 93 (or 94 on Flatpak (and likely elsewhere as well) as it turns out).

**Comment by gcvl** [comment]
> For the past hour I've been trying to get my extensions to work on UGC 94.0.4606.81 to work on Debian Bookworm. So far I've bumped into:
> 
> * Webpages not loading at all unless HTTPs and uBlock Origin are disabled
>  

Same here on Bullseye.

**Comment by sagarvora** [comment]
I have the same issue on Ubuntu Focal. Any pointers on how to downgrade?

**Comment by markozajc** [comment]
@sagarvora I don't think OBS keeps an archive of releases, but I could be wrong. Your best bet would probably be checking out the commit for 93 in this repository (not sure which and on which branch), and building it manually.

**Comment by awsms** [comment]
No page will load for me, even after disabling every single extension.
Using Mint 20

edit: works after relaunching the browser twice.

**Comment by ghost** [comment]
I'm seeing various browser operations hang, it can be midway while loading a web page, installing or updating an extension, or clearing the cache.
At first after starting the browser I can open a page or two and as soon as something gets stuck, subsequent operations hang indefinitely, such as attempting to load a new page, etc., at some point pages don't even begin to load at all anymore.
Indeed disabling all extensions doesn't seem to make everything work properly.

**Comment by markozajc** [comment]
I've observed similar symptoms here too. The browser hung and wouldn't respond anymore after resuming from STR, and generally acted very unresponsive. Could this be an issue with the new memory allocator?

**Comment by sagarvora** [comment]
I think the new `unified` build isn't working as expected. Perhaps someone can try the Flatpak to see if the issue persists

**Comment by markozajc** [comment]
@sagarvora It looks like the release from Flatpak doesn't have these problems (which probably means they're also localized to this project, not ungoogled-chromium in general).
I've tried installing uMatrix on a new profile and importing my ruleset on both:
- Flatpak: installed the extension (unpacked), and imported and committed the ruleset without problems
- Debian: took two tries to install the extension, hung when importing the ruleset

There's definitely something up with the unified build.

**Comment by ghost** [comment]
Tried with a brand new profile (rm -rf rm -rf .cache/chromium/*; mv .config/chromium .config/chromium-1) and so far it seems to be working.
Opening several tabs in several windows, and installed one extension (Proxy SwitchyOmega, hard to live without in this ehhm particular country) and so far so good. The only problem I've noticed so far was in the chrome://extensions/ page, it's just erratic, I had to repeatedly try several methods to install the extensions ("Developer Mode" enabled) and it suddenly just worked by dragging and dropping the .crx file, on the n'th attempt.

**Comment by markozajc** [comment]
> Tried with a brand new profile (rm -rf rm -rf .cache/chromium/*; mv .config/chromium .config/chromium-1) and so far it seems to be working. Opening several tabs in several windows, and installed one extension (Proxy SwitchyOmega, hard to live without in this ehhm particular country) and so far so good. The only problem I've noticed so far was in the chrome://extensions/ page, it's just erratic, I had to repeatedly try several methods to install the extensions ("Developer Mode" enabled) and it suddenly just worked by dragging and dropping the .crx file, on the n'th attempt.

Did not work for me with uMatrix, same issue as before.

**Comment by ghost** [comment]
Now I tried adding uBlock Origin and everything immediately stopped working. Disabling it on the chrome://extensions/ page immediately made the pending page loads go ahead and complete. This is on the fresh profile, better result than on my exisiting one.

**Comment by ghost** [comment]
And, it's rapidly degrading. At this point (uBlock Origin disabled) some specific pages consistently hang halfway while loading.

**Comment by a-kriya** [comment]
@markozajc Anything we can do to help figure out the issue here? What are the differences with the Flatpak build in configuration?

**Comment by markozajc** [comment]
@a-kriya I'm not a maintainer.

**Comment by a-kriya** [comment]
@markozajc My bad.

@braewoods Are you going to be able to help with this? Is there any other member of @ungoogled-software that we can bring this in attention of?

**Comment by ghost** [comment]
@a-kriya You're asking me an impossible question. I don't even know what's causing this. And I don't know chromium that well to even know where to begin to look. All I can guess is it's something to do with packaging differences.

**Comment by awsms** [comment]
@a-kriya
not the first time debian builds are f*cked up, there was another severe issue in a recent build (where the browser would randomly crash). you have to ask this to debian chromium's maintainers (chromium@packages.debian.org).

**Comment by markozajc** [comment]
@awsms I believe ungoogled-chromium-debian doesn't take from debian's downstream since 94.

**Comment by ghost** [comment]
That is correct now. I am currently seeing if Chromium 95 helps at all before looking at the packaging again.

**Comment by ghost** [comment]
I am currently building Chromium 95 on OBS testing repository. I'll see if there's any new build breakage.

**Comment by ghost** [comment]
On the bright side seems Impish is finally working now.

**Comment by ghost** [comment]
I speak too soon. Still some kind of build issue with Impish. I've sent an updated build to OBS after fixing build failure with Sid.

**Comment by ghost** [comment]
I'll do a manual build of Impish since OBS still isn't working currently.

**Comment by ghost** [comment]
Ok. I just tagged chromium 95 since it works well enough to build. Let me know if the problem is still present. If it is I'll look into some other things I haven't tried yet.

**Comment by ghost** [comment]
Also if anyone cares to try their hand at fixing it I'm willing to review PRs.

**Comment by awsms** [comment]
@braewoods: will the v95 builds be available on opensuse repo any time soon for other distros as well? (if you're the one managing it)

**Comment by ghost** [comment]
Whenever OBS gets around to building them. x86_64 is still delayed by lack of available workers.

**Comment by markozajc** [comment]
I have built the package manually on my system, and it seems that upgrading to Chromium 95 did not resolve the issues.

**Comment by ghost** [comment]
Ok, can you document your exact process for reproducing it from a fresh profile? I need something to test against if I am going to get anywhere.

**Comment by markozajc** [comment]
Firstly:
1) Download and extract uMatrix: https://github.com/gorhill/uMatrix/releases/download/1.4.4/uMatrix_1.4.4.chromium.zip
2) Download 5000 dummy uMatrix rules: https://files.zajc.eu.org/unlist/5000-rules.txt

After you're done, run Chromium
1) Head to chrome://extensions/
2) Enable 'Developer mode'
3) Click 'Load unpacked'
4) Select your unextracted uMatrix directory
5) If the extension doesn't show up, click 'Load unpacked' again and exit out of the file selection prompt (for some reason it won't install the extension unless you do that, that's another bug that doesn't occur on the Flatpak release)
6) Click 'Details' on the uMatrix extension card
7) Scroll down and click 'Extension options'
8) Click the 'My Rules' tab
9) Do one of the following
- Click 'Import from file'
 1) Select the '5000-rules.txt' file
 2) Nothing happens, yet the file should be imported
- Copy and paste '5000-rules.txt' into the right textbox
 1) Click 'Save'
 2) If you get past the initial hang, click 'Commit'
 3) Browser hangs.

**Comment by dkebler** [comment]
Reporting that I used the flatpak build and all is good with 95.0.4638.54.    What is different about that build?  Who is responsible for that build anyway?

FYI in focal I had to use the flatpak ppa to get the latest version (universe was way stale) otherwise this version of ungoogled would not install https://flatpak.org/setup/Ubuntu/

**Comment by ghost** [comment]
As reported in https://github.com/Eloston/ungoogled-chromium/issues/1703 and https://github.com/Eloston/ungoogled-chromium/issues/1698, confirmed with a new profile on self-built ungoogled-chromium-debian 95.0.4638.54-1

- Head to chrome://extensions/
- Enable 'Developer mode'
- Drag in the .crx file for uBlock Origin 1.38.6. Note: I have to do this 3 times. It fails on the first two attempts, and in the terminal I see 3 x of "*** stack smashing detected ***: terminated" per attempt.
- As soon as the extension is installed, it seems all page loads fail.

**Comment by Eloston** [comment]
@braewoods I just took a quick look through `unified` for the first time, and you have a pretty novel setup. As a result, I'm not sure if this will help you, but I have a working version of unportable here: https://github.com/ungoogled-software/ungoogled-chromium-debian/commit/a3103329c50da74ea5736892439981dd186e19ea

* Builds version 94.0.4606.81 on Bullseye
* Uses LLVM 13 from apt.llvm.org and `node-typescript` from testing/sid
* Tested configurations: I am using this code right now on GNOME Wayland, and confirmed Pipewire works for screensharing. VA-API does not work on Wayland (but I tested it works on X11). CSD works with GTK+3 theming (which wasn't working in 93).
* NOTE: CI is failing because I didn't refresh the patches, but I'm intending to update it to version 95 soon for my own use.

I do intend to switch to unified eventually, but I haven't dived into all the details of unified yet to see if it fits my use-case

**Comment by peebowo** [comment]
Same thing here on Devuan Ceres.

**Comment by ghost** [comment]
New 95 release merged into `unified`. I am going to see if it builds on OBS and then start trying some tweaks to address the issue here.

**Comment by ghost** [comment]
Well at least all the remaining Impish specific issues on OBS have been fixed. So now just need to figure out what's going on with the builds in general.

**Comment by ghost** [comment]
Part of the problem has been resolved by adding back the launcher flags I omitted. At least it appears to allows the extensions page to import extensions without issue now. I still need to see if there's any solution for the slow import loading.

**Comment by shaheenfawzy** [comment]
Are there any updates regarding this issue?

**Comment by ghost** [comment]
Not really, no. I'm only one guy and haven't managed to find the problem yet.

**Comment by GarikTester** [comment]
> Not really, no. I'm only one guy and haven't managed to find the problem yet.

You can always look at this guy's recipe - he never gets a single glitch. Everything related to build options, patches, etc. Besides, its build is unified. 

http://www.slackware.com/~alien/slackbuilds/chromium-ungoogled/build/chromium.SlackBuild - build recipe.
http://www.slackware.com/~alien/slackbuilds/chromium-ungoogled/build/  - build directory (patches, icons etc.)
http://www.slackware.com/~alien/slackbuilds/chromium-ungoogled/pkg64/current/chromium-ungoogled-95.0.4638.69-x86_64-1alien.lst  - ready package contents (version at the moment).

**Comment by mpaunovic** [comment]
ping @braewoods

Hey man, it's been three months, no word from you. Hope you're doing alright.

Any progress?

**Comment by a-kriya** [comment]
Steps outlined in https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/266#issuecomment-980445614 are a workaround, and it's been working well for me. Just get the latest files from [/Eloston/ungoogled-chromium-binaries/releases](https://github.com/Eloston/ungoogled-chromium-binaries/releases) instead.

**Comment by JamesClarke7283** [comment]
> I have the same issue on Ubuntu Focal. Any pointers on how to downgrade?

I would advise against that for any web browser, downgrading an already 18+ month out of date browser(Chromium 94) is quite dangerous.

Browsers are one of the most targeted and sensitive software you have, because if JavaScript is enabled then its basically running code from the web on your computer, it has a sandbox, but its not full-proof and extended use of outdated browsers are likely to lead to security issues.

See issue #291 for an example. Likely there are other high impact/low effort vulns as they get reported often in browsers/web engines.

If this is for testing purposes only to work out how to fix it, then this is not likely to be high risk.

Perhaps try building from source from a recent, stable release tag, or try using an up-to-date Flatpak or AppImage of it, might solve this issue for you.

**Comment by ghost** [comment]
Issue no longer reproducible on latest version.
