### ISSUE TITLE
Failing to install on Ubuntu 21.10

### ISSUE THREAD

**Issue by VariabileAleatoria** [ungoogled-software/ungoogled-chromium-debian#248]
`curl -s 'https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Impish/Release.key' | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home-ungoogled_chromium.gpg > /dev/null` is failing because the URL gives 404 error

**Comment by markozajc** [comment]
Looks like Impish isn't being built for some reason.
https://build.opensuse.org/package/binaries/home:ungoogled_chromium/ungoogled-chromium-debian/Ubuntu_Impish

**Comment by awsms** [comment]
> Looks like Impish isn't being built for some reason. https://build.opensuse.org/package/binaries/home:ungoogled_chromium/ungoogled-chromium-debian/Ubuntu_Impish

"The build can not begin, because required packages are either missing or not explicitly defined.

unresolvable: nothing provides libllvm11 = 1:11.0.1-2ubuntu4 needed by lld-11, (got version 1:11.0.1-2ubuntu5), nothing provides libllvm11 = 1:11.0.1-2ubuntu4 needed by llvm-11-dev, (got version 1:11.0.1-2ubuntu5), nothing provides gcc-11 >= 11.2.0-1~ needed by gcc, (got version 11.1.0-2ubuntu1)"

**Comment by ghost** [comment]
I'm assuming it's an OBS issue as I was able to complete the build in a local Impish container. I have more serious issues to investigate right now as there's apparently something breaking extensions with the new packaging set.

**Comment by Polve** [comment]
Even the PGP key is not available anymore, this url gives error:
https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Impish/Release.key

**Comment by ghost** [comment]
It never existed because we haven't yet built any Impish packages. It's an OBS issue still.

**Comment by Kwaskoff** [comment]
> Even the PGP key is not available anymore, this url gives error: https://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Impish/Release.key

@polve you can use this thread 

```
echo 'deb http://download.opensuse.org/repositories/home:/ungoogled_chromium:/testing/Ubuntu_Impish/ /' | sudo tee /etc/apt/sources.list.d/home:ungoogled_chromium:testing.list
curl -fsSL https://download.opensuse.org/repositories/home:ungoogled_chromium:testing/Ubuntu_Impish/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_ungoogled_chromium_testing.gpg > /dev/null
sudo apt update
sudo apt install ungoogled-chromium
```

**Comment by ghost** [comment]
@Kwaskoff That's not intended for actual use.

**Comment by docop** [comment]
Could a simple Appimage be made available ? This can make the soft fully portable and fully working directly.

**Comment by markozajc** [comment]
AppImage builds are managed elsewhere: https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/appimage/ (seems a bit outdated, maybe more work could be put into it); this project is for builds compatible with Debian's package management and building system.

**Comment by docop** [comment]
Oh.. indeed . will look forward for an updated version there, as yes, a bit delayed.. hehe
