### ISSUE TITLE
Can't install on Mx linux

### ISSUE THREAD

**Issue by Fallast** [ungoogled-software/ungoogled-chromium-debian#252]
i followed the instructions but this is what i get
`
The following packages have unmet dependencies:
 ungoogled-chromium : Depends: libc6 (>= 2.29) but 2.28-10 is to be installed
                      Depends: libevent-2.1-7 (>= 2.1.8-stable) but it is not installable
                      Depends: libfreetype6 (>= 2.10.1) but 2.9.1-3+deb10u2 is to be installed
                      Depends: libjpeg8 (>= 8c) but it is not installable
                      Depends: libsnappy1v5 (>= 1.1.8) but 1.1.7-1 is to be installed
E: Unable to correct problems, you have held broken packages.
`
i used to have ungoogled chromium but the version 90, i can't remember the exact version or how i installed it, but i deleted it and now i can't seem to install it again

**Comment by markozajc** [comment]
Your distribution's packages are outdated.

**Comment by ghost** [comment]
We don't support Buster or distributions based on it anymore. Please upgrade and try again.
