### ISSUE TITLE
Page Unresponsive errors immediately after update (duplicate)

### ISSUE THREAD

**Issue by RanTrycl** [ungoogled-software/ungoogled-chromium-debian#253]
Version 94.0.4606.81 (Official Build, ungoogled-chromium) Ubuntu (64-bit)

running on 20.4

Immediately after updating UC, the sites I'm logged into such as forums, or sites with heavy scripting, have gone mostly unresponsive.

Pages hang indefinitely with "page unresponsive" error. The page can be reached by quitting and restarting chromium, but only one page displays normally before the "page unresponsive" errors and indefinite hanging behavior crops up again.

Please let me know what to include for better troubleshooting on this.

**Comment by markozajc** [comment]
Seems like #247. Currently the only workaround is downgrading to 93 by manually building the older package.

**Comment by RanTrycl** [comment]
Oh I see, yes, same issue, thank you. Should I delete this?

**Comment by markozajc** [comment]
You could close it.

**Comment by awsms** [comment]
> Seems like #247. Currently the only workaround is downgrading to 93 by manually building the older package.

Could we have a hint how to aim for a certain version when building? I've never done this before

**Comment by markozajc** [comment]
Instructions on building 93 are in the pre-unified branches. If you want to build something older, you'll have to dig a bit, but 93 should work for the most part.

Copy-paste the build instructions into a terminal (preferably line-by-line, ignoring comments).
```bash
# Install essential requirements
sudo apt install git python3 packaging-dev equivs

# Clone the repository and its submodules
git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-debian.git

# NOTE: If you are reading this on GitHub, make sure to read the version corresponding
# to your checkout of this repo (replace TAG_OR_BRANCH_HERE with the tag or branch you want to build):
# https://github.com/ungoogled-software/ungoogled-chromium-debian/blob/TAG_OR_BRANCH_HERE/README.md
#
# Or, just read the README in your local repo.

# Replace TAG_OR_BRANCH_HERE with the tag or branch you want to build (optional)
# Example of a tag: 79.0.3945.88-1.sid1
# Example of a branch: debian_sid
git -C ungoogled-chromium-debian checkout --recurse-submodules TAG_OR_BRANCH_HERE

# Setup build tree under build/
mkdir -p build/src
cp -r ungoogled-chromium-debian/debian build/src/
cd build/src

# Final setup steps for debian/ directory
./debian/scripts/setup debian

# Install remaining requirements to build Chromium
sudo mk-build-deps -i debian/control
rm ungoogled-chromium-build-deps_*

# Download and unpack Chromium sources (this will take some time)
./debian/scripts/setup local-src

# Start building
dpkg-buildpackage -b -uc
```
If you want UGC to build faster (it usually takes quite a while), add `-j<number>` to `dpkg-buildpackage`, number being the amount of threads to build with.

After UGC is built, uninstall your current ungoogled-chromium and install the resulting packages with apt.
