### ISSUE TITLE
apt remove issues

### ISSUE THREAD

**Issue by arthurlch** [ungoogled-software/ungoogled-chromium-debian#262]
I want to uninstall the software from my machine. 

Apt list result : ungoogled-chromium-common/unknown 90.0.4430.212-1.hirsute1 amd64
ungoogled-chromium-common/unknown 90.0.4430.212-1.hirsute1 arm64
ungoogled-chromium-common/unknown 90.0.4430.212-1.hirsute1 armhf
ungoogled-chromium-driver/unknown 90.0.4430.212-1.hirsute1 amd64
ungoogled-chromium-driver/unknown 90.0.4430.212-1.hirsute1 arm64
ungoogled-chromium-driver/unknown 90.0.4430.212-1.hirsute1 armhf
ungoogled-chromium-l10n/unknown 90.0.4430.212-1.hirsute1 all
ungoogled-chromium-sandbox/unknown 90.0.4430.212-1.hirsute1 amd64
ungoogled-chromium-sandbox/unknown 90.0.4430.212-1.hirsute1 arm64
ungoogled-chromium-sandbox/unknown 90.0.4430.212-1.hirsute1 armhf
ungoogled-chromium-shell/unknown 90.0.4430.212-1.hirsute1 amd64
ungoogled-chromium-shell/unknown 90.0.4430.212-1.hirsute1 arm64
ungoogled-chromium-shell/unknown 90.0.4430.212-1.hirsute1 armhf
ungoogled-chromium/unknown 90.0.4430.212-1.hirsute1 amd64
ungoogled-chromium/unknown 90.0.4430.212-1.hirsute1 arm64
ungoogled-chromium/unknown 90.0.4430.212-1.hirsute1 armhf

issue : Apt cannot remove the package 
sudo apt remove ungoogled-chromium
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'ungoogled-chromium' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 191 not upgraded.

However the software is functional and installed on the machine.
To be sure that it wasn't installed via other methods, I decided to check other files and couldn't see other packages. Except the one already installed in the apt repo. 

Currently running Pop!_OS 21.04 5.13.9-051309-generic

**Comment by markozajc** [comment]
> Apt list result :

`apt list` by default lists all available packages. You need to use the `--installed` flag to only get the installed packages, which I'm not sure if you did.

Please send the output of `dpkg -l | grep chromium`, `dpkg -S "$(whereis chromium | awk '{print $2}')"`, and `whereis chromium`

**Comment by arthurlch** [comment]
Thanks for your reply & help. 
I didn't know that flag! 

dpkg -l | grep chromium => No output 
dpkg -S "$(whereis chromium | awk '{print $2}')" => chrome-gnome-shell: /etc/chromium
whereis chromium => chromium: /etc/chromium

**Comment by markozajc** [comment]
Looks like chromium is not installed, at least not via apt. Make sure to check flatpak and snap (if you have them). You might also want to check if you have chrome installed.

This is also not a problem with ungoogled-chromium, so you should probably close the issue.
