### ISSUE TITLE
Release binaries for version 96.0.4664.45

### ISSUE THREAD

**Issue by Motor-head** [ungoogled-software/ungoogled-chromium-debian#264]
The last build is still 95.0.4638.54 and I'm relying on debs from this git to install the packages.

**Comment by dkebler** [comment]
so if I understand correctly this will not resolve #247

**Comment by markozajc** [comment]
I believe not. The unified build currently has problems due to its configuration, not because it's an outdated version.

**Comment by Eloston** [comment]
Released new binaries for unportable: https://github.com/Eloston/ungoogled-chromium-binaries/releases/tag/95.0.4638.69-1.unportable1
