### ISSUE TITLE
page chrome://flags/ freezes

### ISSUE THREAD

**Issue by xoxloviwan** [ungoogled-software/ungoogled-chromium-debian#269]
page chrome://flags/ freezes on version

`http://download.opensuse.org/repositories/home:/ungoogled_chromium/Ubuntu_Focal  ungoogled-chromium 95.0.4638.54-1 [76,8 MB]`

and then crashed with code error 5.

`5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by markozajc** [comment]
Likely a duplicate of #247. Install [Eloston's unportable builds](https://github.com/Eloston/ungoogled-chromium-binaries/releases) as a workaround (NB: they're built on Debian Bullseye, so they might not work on Ubuntu. You'll have to compile it yourself in that case).

**Comment by xoxloviwan** [comment]
> Likely a duplicate of #247. Install [Eloston's unportable builds](https://github.com/Eloston/ungoogled-chromium-binaries/releases) as a workaround (NB: they're built on Debian Bullseye, so they might not work on Ubuntu. You'll have to compile it yourself in that case).

I install https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium-common_95.0.4638.69-1.unportable1_amd64.deb
and
https://github.com/Eloston/ungoogled-chromium-binaries/releases/download/95.0.4638.69-1.unportable1/ungoogled-chromium_95.0.4638.69-1.unportable1_amd64.deb
and this treats it
