### ISSUE TITLE
chrome://flags/ is not response

### ISSUE THREAD

**Issue by an1ndra** [ungoogled-software/ungoogled-chromium-debian#275]
![Screenshot from 2021-12-31 10-23-56](https://user-images.githubusercontent.com/36324543/147806263-93e04e1b-ea9f-42c4-8a95-48cc982cf07f.png)
Every time when I open chrome://flags/ my tab become unresponsive.
I am using Pop os 21.10

**Comment by Eloston** [comment]
Duplicate of #247. Please use unportable for now, thanks.
