### ISSUE TITLE
Symbol lookup error at start

### ISSUE THREAD

**Issue by tsilvs** [ungoogled-software/ungoogled-chromium-debian#278]
# System
- Ubuntu 20.04
- libjsoncpp1 1.7.6
- ungoogled-chromium 95.0.4638.54-1
# Description
Trying to run `chromium` command leads to a message:
> `/usr/lib/chromium/chrome: symbol lookup error: /usr/lib/chromium/chrome: undefined symbol: _ZN4Json5ValueC1Ex`

So it might be that some JSON value was poorly compiled.

`grep -rlw "_ZN4Json5ValueC1Ex" /usr/lib` found only one file that contains this string - `/usr/lib/chromium/chrome`

A brief online search showed that this issue might be related to `jsoncpp` somehow, specifically to v1.7.4.

**Comment by tsilvs** [comment]
Issue is still relevant. Who should I send this bug report to, if describing it here is not enough?

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.
