### ISSUE TITLE
Raspberry Pi 4B (Debian 11 bullseye armhf) builds

### ISSUE THREAD

**Issue by nandlab** [ungoogled-software/ungoogled-chromium-debian#279]
The latest Raspberry Pi OS is based on Debian 11 (bullseye) armhf. Are there any builds for this platform? On [OBS](http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Bullseye/) I do not see any files in the armhf directory. It would be awesome, if I could use ungoogled-chromium instead of the default chromium (with telemetry, floc, etc.) on the Raspberry Pi :-)

**Comment by ghost** [comment]
We no longer build armhf, only aarch64.

**Comment by nandlab** [comment]
Sorry for interrupting, but have their been any issues building for armhf? Maybe I could try to build it myself.

**Comment by ghost** [comment]
Not to my knowledge but it's becoming harder to build for. I didn't factor it into my setup scripts and patches for the node binaries for one. If you manage to get it working for armhf, I can accept it as a PR. I just didn't want to mess with all the work required to get the correct architecture specific strings. It was enough of a hassle for arm64.
