### ISSUE TITLE
Build failure on Debian 11

### ISSUE THREAD

**Issue by joshaspinall** [ungoogled-software/ungoogled-chromium-debian#280]
Build failure on Debian 11, as per instructions: [instructions](https://github.com/ungoogled-software/ungoogled-chromium-debian)

Paste of logs here: [log](https://paste.debian.net/1229680/)

**Comment by ghost** [comment]
Expected. In the middle of an upgrade.

**Comment by joshaspinall** [comment]
Thanks, will keep an eye on the feed and re-try soon.
