### ISSUE TITLE
Unable to upload/download file

### ISSUE THREAD

**Issue by ivbit** [ungoogled-software/ungoogled-chromium-debian#285]
I did a clean install of Debian 11.2.0 with Xfce4 desktop environment and then built from source ungoogled-chromium 98.0.4758.80.
The browser works perfectly fine except it is unable to upload any file from disk, download any file to disk and even load the extension's settings page from disk. When I try to download a file, the dialog box opens, I select the location and then nothing happens. Same thing with uploading. Am I missing a dependency here?
If you need it, the binary file I built can be downloaded from here:
https://codeberg.org/ivanb/myUngoogledBuild/raw/branch/main/ungoogled98MyBuild.deb

**Comment by wilkemeyer** [comment]
I've noticed the same behavior 
Self build, same version, fully patched xubuntu 21.10 

About downloading: when starting a download, the location dialog opens, after choosing the save location the download does not appear in the downloads tab

When monitoring my networking i see that a filetransfer is in progress.



I've also got a problem when i open chrome://flags the tab freezes after 1-2 seconds
Can you check if you've got the same problem? 

Maybe those two problems relate to each other.



_Additional Info:_
No Problems with ubuntu's chromium via snap (Version 98.0.4758.102 (Official Build) snap (64-bit))

**Comment by ghost** [comment]
It's to be expected, you're using a pre-release. I still haven't been able to trace the performance issues.

**Comment by ivbit** [comment]
I should also mention that it's an amd64 system.
**wilkemeyer**, the chrome://flags opens without a delay; I also have network activity when trying to download a file; when I close the browser, it warns me about download in progress.
**braewoods**, if I understood you correctly, I should be using the latest tag instead. Currently it's **95.0.4638.54-1**. Is this correct?

**Comment by markus2330** [comment]
I have the same problem with http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Bullseye/./amd64/ungoogled-chromium_95.0.4638.54-1_amd64.deb

Also printing to pdf does not work.
