### ISSUE TITLE
Couple Issues

### ISSUE THREAD

**Issue by pup-tv** [ungoogled-software/ungoogled-chromium-debian#287]
1.)  Ungoogled Chromium 95.0.4638.54 Official Build on up to date Debian 11

Unable to *relaunch* (Save) anything in chrome://flags. chrome://settings works fine.  (Also can't use mouse to change any setting in //flags, but can use the keyboard.)

get lots of Page Unresponsive missives while trying.

No error messages sent to terminal.

2.)  Terra Station web app is blank.

Terminal error: child_thread_impl.cc (339) Crashing because hung

Thanks for all of the great work...

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.
