### ISSUE TITLE
Another name, etc. beside Chromium?

### ISSUE THREAD

**Issue by burdges** [ungoogled-software/ungoogled-chromium-debian#288]
Ideally ungoogled-chromium would be entirely separate from regular chromium, making it distinguishable in gnome menus.

Also users should copy chrome settings urls from regular chromium, and bookmark them, because the setitngs menu lacks its navigation sidebar.

**Comment by PF4Public** [comment]
See the [README.md](https://github.com/Eloston/ungoogled-chromium/blob/master/README.md#objectives) (emphasis mine):

> ungoogled-chromium retains the default Chromium experience as closely as possible. Unlike other Chromium forks that have their own visions of a web browser, *ungoogled-chromium is essentially a drop-in replacement for Chromium*.

**Comment by burdges** [comment]
Alright things, makes sense.

I suppose the correct issue would then be to add navigation for the settings menu.

I also noticed extensions do not work, which exists as #245
