### ISSUE TITLE
usefulness of debian/disable/tracing.patch 

### ISSUE THREAD

**Issue by zrose584** [ungoogled-software/ungoogled-chromium-debian#29]
What about removing `debian/disable/tracing.patch` from `debian/series/`?
Background info: [[1]](https://github.com/GoogleChrome/lighthouse/issues/7246) [[2]](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922431#10).
opinions?

**Comment by Eloston** [comment]
It's already gone on Debian buster. I didn't really like their decision to break tracing because of minified JS files.
