### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [ungoogled-software/ungoogled-chromium-debian#294]
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/

**Comment by mpaunovic** [comment]
Sorry to say but I don't think their privacy policy gets along well with ungoogled-chromium.

https://pacstall.dev/privacy

**Comment by networkException** [comment]
Why would that matter?

**Comment by trymeouteh** [comment]
If not, maybe create your own pacstall repository and maintain ungoogled chromium on the self hosted repository, or find another pacstall repository to host ungoogled chromium on.

**Comment by ghost** [comment]
I know this is late, but why would we use this over our existing OBS repository? I know it has had its issues but this wouldn't magically fix them.

**Comment by ghost** [comment]
I've not heard from the reporter so I am closing this. I can't see any value in Pacstall when we have OBS.
