### ISSUE TITLE
Missing dependencies on Debian Sid

### ISSUE THREAD

**Issue by ernobe** [ungoogled-software/ungoogled-chromium-debian#295]
As per Debian bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1005230
libgtk-3-0 was removed from dependencies causing failure to run with a 

"trace/breakpoint trap" error.  

Fixed it by installing libgtk-3-0:amd64 and related dependencies.

**Comment by joshaspinall** [comment]
FWIW I also have tried to install on Sid.  Missing two different dependencies:

> sudo apt install -y ungoogled-chromium
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ungoogled-chromium : Depends: libjsoncpp24 (>= 1.9.4) but it is not installable
                      Depends: libwebp6 (>= 0.5.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by ernobe** [comment]
I had to install those packages manually.  They are from a previous stable version of Debian.  Just go to the Debian website, search for them, download them, and install with dpkg -i.

**Comment by ernobe** [comment]
I thought berkley4 was the main repository of ungoogled-chromium.

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.
