### ISSUE TITLE
Create Packages for Ubuntu 22.04 (Jammy) 

### ISSUE THREAD

**Issue by rambalachandran** [ungoogled-software/ungoogled-chromium-debian#296]
Please create an installation package for the latest Ubuntu LTS 22.04 (Jammy).

**Comment by mpaunovic** [comment]
Maybe this will help:

https://github.com/berkley4/ungoogled-chromium-debian/releases/latest

https://github.com/berkley4/ungoogled-chromium-debian#installation

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.
