### ISSUE TITLE
Auto Launch Ungoogled Chrome on Start up rasperberry pi

### ISSUE THREAD

**Issue by ecosse69** [ungoogled-software/ungoogled-chromium-debian#297]
I am trying to get ungoogled chromium to launch on startup from a script similar to the following on a Raspberry Pi. It will effectively show a web page which displays on a screen at the entrance to a room. The script works fine with standard chromium but fails to find ungoogled chromium.

****************************

#!/bin/sh
DISPLAY=:0 xrandr --output HDMI-1 --rotate right
xset -dpms     # disable DPMS (Energy Star) features.
xset s off     # disable screen saver
xset s noblank # don't blank the video device
matchbox-window-manager -use_titlebar no &
unclutter &    # hide X mouse cursor unless mouse activated
chromium-browser --display=:0 --kiosk --incognito --window-position=0,0 http://some-web-address

********************************

**Comment by PF4Public** [comment]
> but fails to find ungoogled chromium

Please be more specific: what fails exactly? Any logs? How did you install ungoogled-chromium?

**Comment by ghost** [comment]
User failed to respond in a timely manner and this is really more a help question than an actual bug report.
