### ISSUE TITLE
Debian Sid uninstall instructions?

### ISSUE THREAD

**Issue by harukayamazaki** [ungoogled-software/ungoogled-chromium-debian#298]
I have not be able to find proper documentation on uninstalling this software for the Debian Sid build. Any help would be appreciated

**Comment by harukayamazaki** [comment]
I don't simply mean to uninstall the package, I understand the concept, just not how to purge the sources and configs completely.

**Comment by ernobe** [comment]
Normally that would be with dpkg --purge.

**Comment by ghost** [comment]
This isn't something we document because it just uses the standard methods available to the package manager. Refer to apt's documentation to find out more.
