### ISSUE TITLE
Unable to install stable version 102.0.5005.61-1  on Ubuntu Jammy

### ISSUE THREAD

**Issue by Kerbecode** [ungoogled-software/ungoogled-chromium-debian#299]
I've recently installed Ubuntu 22.04 LTS but when I run dkpg -i to install the packet I get dependency errors.
Do you have any idea about when Ubuntu 22.04 LTS will be supported ?

**Comment by berkley4** [comment]
Can you post up the error message? Without that nobody would have much idea what the exact problem is.

**Comment by Kerbecode** [comment]
This is what I got :
It seems like a package that ungoogled-chromium requires cannot be install on my system 

![ungoogled-chromium_installationProblem](https://user-images.githubusercontent.com/97767477/174016297-b5a9e2f1-4ad4-432d-9cad-96c002480537.png)

**Comment by original-birdman** [comment]
`libjsoncpp24` may also be expected, but Jammy has `libjsoncpp25`.

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.
