### ISSUE TITLE
native messaging portal not working in flatpak - keepassxc plugin not working

### ISSUE THREAD

**Issue by chymian** [ungoogled-software/ungoogled-chromium-debian#308]
since there is no debian package on OBS available, I had to use the flatpak on bullseye with the effect, that the keepassxc plugin is not working. see also bug https://github.com/keepassxreboot/keepassxc/issues/8410.
this is a show-stopper.

**Comment by networkException** [comment]
This is not related to debian packaging, please report it in the flatpak packaging repo: https://github.com/flathub/com.github.Eloston.UngoogledChromium
