### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by hyperlogos** [ungoogled-software/ungoogled-chromium-debian#310]
Just tried now on Ubuntu Jammy. Here's the end of the log.

ninja: Entering directory `/home/drink/Software/ungoogled-chromium-debian/out/Release/gn_build'
[1/194] CXX src/base/files/file_path_constants.o
FAILED: src/base/files/file_path_constants.o 
clang++-11 -MMD -MF src/base/files/file_path_constants.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/file_path_constants.cc -o src/base/files/file_path_constants.o
../../../tools/gn/src/base/files/file_path_constants.cc:7:10: fatal error: 'iterator' file not found
#include <iterator>
         ^~~~~~~~~~
1 error generated.
[2/194] CXX src/base/json/json_reader.o
FAILED: src/base/json/json_reader.o 
clang++-11 -MMD -MF src/base/json/json_reader.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/json/json_reader.cc -o src/base/json/json_reader.o
In file included from ../../../tools/gn/src/base/json/json_reader.cc:5:
../../../tools/gn/src/base/json/json_reader.h:31:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
[3/194] CXX src/base/files/file_path.o
FAILED: src/base/files/file_path.o 
clang++-11 -MMD -MF src/base/files/file_path.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/file_path.cc -o src/base/files/file_path.o
In file included from ../../../tools/gn/src/base/files/file_path.cc:5:
../../../tools/gn/src/base/files/file_path.h:107:10: fatal error: 'iosfwd' file not found
#include <iosfwd>
         ^~~~~~~~
1 error generated.
[4/194] CXX src/base/environment.o
FAILED: src/base/environment.o 
clang++-11 -MMD -MF src/base/environment.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/environment.cc -o src/base/environment.o
In file included from ../../../tools/gn/src/base/environment.cc:5:
../../../tools/gn/src/base/environment.h:8:10: fatal error: 'map' file not found
#include <map>
         ^~~~~
1 error generated.
[5/194] CXX src/base/command_line.o
FAILED: src/base/command_line.o 
clang++-11 -MMD -MF src/base/command_line.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/command_line.cc -o src/base/command_line.o
In file included from ../../../tools/gn/src/base/command_line.cc:5:
../../../tools/gn/src/base/command_line.h:19:10: fatal error: 'map' file not found
#include <map>
         ^~~~~
1 error generated.
[6/194] CXX src/base/json/json_writer.o
FAILED: src/base/json/json_writer.o 
clang++-11 -MMD -MF src/base/json/json_writer.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/json/json_writer.cc -o src/base/json/json_writer.o
In file included from ../../../tools/gn/src/base/json/json_writer.cc:5:
../../../tools/gn/src/base/json/json_writer.h:10:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
[7/194] CXX src/base/files/scoped_file.o
FAILED: src/base/files/scoped_file.o 
clang++-11 -MMD -MF src/base/files/scoped_file.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/scoped_file.cc -o src/base/files/scoped_file.o
In file included from ../../../tools/gn/src/base/files/scoped_file.cc:5:
../../../tools/gn/src/base/files/scoped_file.h:10:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
[8/194] CXX src/base/files/file.o
FAILED: src/base/files/file.o 
clang++-11 -MMD -MF src/base/files/file.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/file.cc -o src/base/files/file.o
In file included from ../../../tools/gn/src/base/files/file.cc:5:
../../../tools/gn/src/base/files/file.h:10:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.
[9/194] CXX src/base/files/scoped_temp_dir.o
FAILED: src/base/files/scoped_temp_dir.o 
clang++-11 -MMD -MF src/base/files/scoped_temp_dir.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/scoped_temp_dir.cc -o src/base/files/scoped_temp_dir.o
In file included from ../../../tools/gn/src/base/files/scoped_temp_dir.cc:5:
In file included from ../../../tools/gn/src/base/files/scoped_temp_dir.h:20:
../../../tools/gn/src/base/files/file_path.h:107:10: fatal error: 'iosfwd' file not found
#include <iosfwd>
         ^~~~~~~~
1 error generated.
[10/194] CXX src/base/files/file_util.o
FAILED: src/base/files/file_util.o 
clang++-11 -MMD -MF src/base/files/file_util.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/file_util.cc -o src/base/files/file_util.o
In file included from ../../../tools/gn/src/base/files/file_util.cc:5:
../../../tools/gn/src/base/files/file_util.h:15:10: fatal error: 'set' file not found
#include <set>
         ^~~~~
1 error generated.
[11/194] CXX src/base/files/file_enumerator.o
FAILED: src/base/files/file_enumerator.o 
clang++-11 -MMD -MF src/base/files/file_enumerator.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/files/file_enumerator.cc -o src/base/files/file_enumerator.o
In file included from ../../../tools/gn/src/base/files/file_enumerator.cc:5:
../../../tools/gn/src/base/files/file_enumerator.h:11:10: fatal error: 'vector' file not found
#include <vector>
         ^~~~~~~~
1 error generated.
[12/194] CXX src/base/json/json_parser.o
FAILED: src/base/json/json_parser.o 
clang++-11 -MMD -MF src/base/json/json_parser.o.d -I../../../tools/gn/src -I. -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -O2 -ffile-prefix-map=/home/drink/Software/ungoogled-chromium-debian=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-unknown-warning-option -D_LIBCPP_HAS_NO_VENDOR_AVAILABILITY_ANNOTATIONS -DNDEBUG -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -c ../../../tools/gn/src/base/json/json_parser.cc -o src/base/json/json_parser.o
In file included from ../../../tools/gn/src/base/json/json_parser.cc:5:
../../../tools/gn/src/base/json/json_parser.h:11:10: fatal error: 'memory' file not found
#include <memory>
         ^~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/drink/Software/ungoogled-chromium-debian/tools/gn/bootstrap/bootstrap.py", line 144, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/drink/Software/ungoogled-chromium-debian/tools/gn/bootstrap/bootstrap.py", line 126, in main
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', '-C', '/home/drink/Software/ungoogled-chromium-debian/out/Release/gn_build', '-w', 'dupbuild=err', '-j12', 'gn']' returned non-zero exit status 1.
make[1]: *** [debian/rules:133: out/Release/gn] Error 1
make[1]: Leaving directory '/home/drink/Software/ungoogled-chromium-debian'
make: *** [debian/rules:107: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.

**Comment by hyperlogos** [comment]
I can now build on Devuan 4
