### ISSUE TITLE
Build fail at the last command

### ISSUE THREAD

**Issue by thepra** [ungoogled-software/ungoogled-chromium-debian#312]
> patching file components/security_interstitials/content/cert_report_helper.cc
> Reversed (or previously applied) patch detected!  Skipping patch.
> 1 out of 1 hunk ignored -- saving rejects to file components/security_interstitials/content/cert_report_helper.cc.rej
> Traceback (most recent call last):
>   File "/ungoogled/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/utils/patches.py", line 250, in <module>
>     main()
>   File "/ungoogled/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/utils/patches.py", line 246, in main
>     args.callback(args, parser.error)
>   File "/ungoogled/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/utils/patches.py", line 198, in _apply_callback
>     apply_patches(
>   File "/ungoogled/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/utils/patches.py", line 132, in apply_patches
>     subprocess.run(cmd, check=True)
>   File "/usr/lib/python3.10/subprocess.py", line 524, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/usr/bin/patch', '-p1', '--ignore-whitespace', '-i', '/ungoogled/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/patches/core/inox-patchset/0001-fix-building-without-safebrowsing.patch', '-d', '/ungoogled/ungoogled-chromium-debian', '--no-backup-if-mismatch', '--forward']' returned non-zero exit status 1.
> make[1]: *** [debian/rules:136: override_dh_auto_configure] Errore 1
> make[1]: uscita dalla directory «/ungoogled/ungoogled-chromium-debian»
> make: *** [debian/rules:107: binary] Errore 2
> dpkg-buildpackage: Errore: debian/rules binary subprocess returned exit status 2

I'm having this failing build at the last step. What's going on?(ps: I'm on linuxmint)

**Comment by ghost** [comment]
New release in progress, this is no longer relevant.
