### ISSUE TITLE
Please made armhf deb package for Debian Bullseye which is still current status of Debian Stable

### ISSUE THREAD

**Issue by 00shadows** [ungoogled-software/ungoogled-chromium-debian#326]
As seen on [ungoogled-chromium Official Repo](http://download.opensuse.org/repositories/home:/ungoogled_chromium/) this build is not available for Debian Bullseye armhf. Dude I am still using old Orange Pi Lite which using 512MB ram and using Armbian Bullseye, please build for Debian Bullseye armhf.

_Originally posted by @00shadows in https://github.com/ungoogled-software/ungoogled-chromium-debian/issues/315#issuecomment-1557623149_

**Comment by SugaryHull** [comment]
Debian 12 releases in less than 2 weeks. 11 was deprecated here because of that and because the required version of Clang isn't available. Debian has to patch every release of Chromium to build with Clang 13 and, as such, isn't always able to keep up with upstream.

**Comment by 00shadows** [comment]
I updated my oPi to Debian 12, and all just worked. thank you communities for keep supporting ungoogled-chromium
