### ISSUE TITLE
113.0.5672.63-1 fails to build on Ubuntu 23.04 (lunar)

### ISSUE THREAD

**Issue by original-birdman** [ungoogled-software/ungoogled-chromium-debian#329]
```
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:143: override_dh_auto_build] Error 1
make[1]: Leaving directory '/GMLtemp/Ungoogled-Chromium/ungoogled-chromium-debian'
make: *** [debian/rules:109: binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```
Attempting a restart of the build (dpkg-buildpackage -b -uc) at that point produces:
```make[1]: Entering directory '/GMLtemp/Ungoogled-Chromium/ungoogled-chromium-debian'
/GMLtemp/Ungoogled-Chromium/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/utils/patches.py apply /GMLtemp/Ungoogled-Chromium/ungoogled-chromium-debian /GMLtemp/Ungoogled-Chromium/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/patches
INFO: Applying patches from /GMLtemp/Ungoogled-Chromium/ungoogled-chromium-debian/debian/submodules/ungoogled-chromium/patches
INFO: * Applying 0001-fix-building-without-safebrowsing.patch (1/100)
patching file chrome/browser/BUILD.gn
Reversed (or previously applied) patch detected!  Skipping patch.
...(followed by many other "reversed path" failures)
```
which may, or may not,  be the problem.

Although having just read the LinuxMint issue it's actually the same as that.

**Comment by original-birdman** [comment]
I do have libstdc++-12-dev installed.  And this file is there:
```
[gmllaptop]: ls -l /usr/include/c++/12/cmath 
-rw-r--r-- 1 root root 49383 Mar 14 09:40 /usr/include/c++/12/cmath
```

Possibly more relevant (since the compiler at this point is clang++-14) I also have libc++-14-dev installed, which provides:
```
[gmllaptop]: ls -l /usr/lib/llvm-14/include/c++/v1/cmath 
-rw-r--r-- 1 root root 20750 Jun 25  2022 /usr/lib/llvm-14/include/c++/v1/cmath
```
which also shows up (via a symlink) as:
```
[gmllaptop]: ls -l /usr/include/c++/v1/cmath 
-rw-r--r-- 1 root root 20750 Jun 25  2022 /usr/include/c++/v1/cmath
```

**Comment by original-birdman** [comment]
There do seem to be two different (but similar) `bignum-dtoa.cc` implementations in the source.
Bloat?

**Comment by SugaryHull** [comment]
The issue you were experiencing with trying to resume the build is a known issue. Unfortunately, I haven't found a way around it besides just rerunning `debian/rules setup`.

As for the build error, we would need more context than just the final error code in order to debug this. I suspect you're missing some important Debian patches that weren't included in our source tree for this version of Chromium. I've actually been meaning to create a pull request for 114.0.5735.199-1, which I got to build on Debian 12 with some upstream Debian patches.

**Comment by original-birdman** [comment]
Difficult to get any context for the error, as there are so many warnings (mostly about inline) being produced.

But all I want is a chromium that I can use from time to time, and I now see there are working binary installs available, so they'll do for me.
