### ISSUE TITLE
Can't build ungoogled chromium on debian buster

### ISSUE THREAD

**Issue by merfoc** [ungoogled-software/ungoogled-chromium-debian#34]
I have followed instructions and tried five times and same warnings comes every time. What I've done wrong?

In file included from ../../chrome/browser/media/router/discovery/mdns/dns_sd_device_lister.cc:5:
../../chrome/browser/media/router/discovery/mdns/dns_sd_device_lister.h:51:24: warning: private field 'delegate_' is not used [-Wunused-private-field]
  DnsSdDelegate* const delegate_;
                       ^
1 warning generated.
[18753/21809] CXX obj/chrome/browser/ui/ui/ui_jumbo_50.o
In file included from gen/chrome/browser/ui/ui_jumbo_50.cc:16:
In file included from ./../../chrome/browser/ui/sync/one_click_signin_links_delegate_impl.cc:5:
../../chrome/browser/ui/sync/one_click_signin_links_delegate_impl.h:25:18: warning: private field 'browser_' is not used [-Wunused-private-field]
  Browser* const browser_;
                 ^
1 warning generated.
[18770/21809] CXX obj/chrome/browser/ui/ui/ui_jumbo_52.o
In file included from gen/chrome/browser/ui/ui_jumbo_52.cc:13:
In file included from ./../../chrome/browser/ui/webui/signin/inline_login_handler_impl.cc:5:
../../chrome/browser/ui/webui/signin/inline_login_handler_impl.h:186:8: warning: private field 'confirm_untrusted_signin_' is not used [-Wunused-private-field]
  bool confirm_untrusted_signin_;
       ^
1 warning generated.
[18908/21809] CXX obj/chrome/common/common/google_url_loader_throttle.o
In file included from ../../chrome/common/google_url_loader_throttle.cc:5:
../../chrome/common/google_url_loader_throttle.h:39:8: warning: private field 'is_off_the_record_' is not used [-Wunused-private-field]
  bool is_off_the_record_;
       ^
1 warning generated.
[21494/21809] CXX obj/v8/v8_base_without_compiler/v8_base_without_compiler_jumbo_27.o
In file included from gen/v8/v8_base_without_compiler_jumbo_27.cc:10:
./../../v8/src/objects/js-list-format.cc:336:22: warning: implicit conversion loses integer precision: 'std::vector::size_type' (aka 'unsigned long') to 'int' [-Wshorten-64-to-32]
  int length = items.size();
      ~~~~~~   ~~~~~~^~~~~~
1 warning generated.

 dpkg-genbuildinfo --build=binary
 dpkg-genchanges --build=binary >../ungoogled-chromium_78.0.3904.97-2.buster1_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build .


dpkg-buildpackage: info: binary-only upload (no source included)

**Comment by Eloston** [comment]
The warnings look normal to me. The `-Wunused-private-field`s are because the patches don't remove all unused code. The `-Wshorten-64-to-32` resulted from Debian's patch `debian/patches/buster/icu63.patch`.

The log indicates that the packages were built successfully:

```
dpkg-genbuildinfo --build=binary
dpkg-genchanges --build=binary >../ungoogled-chromium_78.0.3904.97-2.buster1_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
dpkg-source --after-build .

dpkg-buildpackage: info: binary-only upload (no source included)
```

Packages always appear in the parent directory of your current working directory. Do you not see them?

**Comment by merfoc** [comment]
Sorry, my mistake. I tried to open the browser terminal and it reported a sandbox missing. Everything is allright now.
