### ISSUE TITLE
Uninstall process for ungoogled-chromium installed using dpkg-buildpackage

### ISSUE THREAD

**Issue by Recouper** [ungoogled-software/ungoogled-chromium-debian#347]
Hi.

I followed the README for ungoogled-chromium-debian a little too literally.

Under the "Getting OBS packages" section, I followed the "OBS Setup Instructions" link and downloaded the .deb package from there. The README for ungoogled-chromium-debian did not say to install that .deb file, so I didn't. I went to the next step in the README, "Building a binary package".

I had some dependency problems and then had the suspicion that was probably meant to be resolved by installing that .deb package I had downloaded from the "OBS Setup Instructions" link. So I installed that and then attempted to continue with the README. I still had the same dependency problems, so I resolved them manually. I finally built the "ungoogled-chromium" browser using the "dpkg-buildpackage -b -uc" command.

But then when I checked that install, I found two Chromium browsers installed in my XFCE "Whisker Menu". Both work and both appear to be the same.

So, I think that .deb package from "Getting OBS packages" actually installed "ungoogled-chromium" and then I went and built it, so ended up with two instances installed on my system.

Is there a way to uninstall the one built using "dpkg-buildpackage"?

Thank you.

**Comment by iskunk** [comment]
Hi @Recouper,

I would suggest running `dpkg -l | grep chromium` to see which Chromium-related packages you have installed. Once you've identified the one(s) you want to get rid of, run e.g. `apt-get --purge remove packagename` (as root) to get 'em out.

That said, I would hesitate to use the package available from OBS at the moment... it hasn't been updated in a long time, and running an old version of the browser leaves you open to numerous security vulnerabilities. Chromium is currently at major release version 127, so anything less than that should be avoided.

(I hope to get automation up and running soon to keep the OBS package current, see #343)

**Comment by Recouper** [comment]
Thank you for your reply. I haven't used dpkg much in the past and didn't realise how much it can do.
