### ISSUE TITLE
get-orig-source fails during prune_binaries script run

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#39]
I setup a working directory, attempting to get a set of files I could upload to an automated build service. However I keep getting an error when the prune_binaries script is run. It fails to remove 18405 files which happens to be how many paths are specified in the list given to it. I think the issue is that the script is given the current working directory as the base instead of the extracted tarball directory so this pruning only works if the local source is extracted first. I suspect this is an oversight and not the intended result. I think changing ./ to use $(extract) instead in the debian/rules file should resolve the matter. Here are the commands I used to produce the issue from a debian 10 container:

`git clone --recurse-submodules https://github.com/ungoogled-software/ungoogled-chromium-debian.git`
`git -C ungoogled-chromium-debian checkout --recurse-submodules 78.0.3904.108-2.bionic1
mkdir ungoogled-chromium`
`cp -r ungoogled-chromium-debian/debian ungoogled-chromium`
`cd ungoogled-chromium`
`debian/rules setup-debian`
`debian/rules get-orig-source`

**Comment by Eloston** [comment]
Yeah, you're right. Thanks for the fix.
