### ISSUE TITLE
differences between get-orig-source and setup-local-src

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#45]
I have discovered a difference between how the two modes setup the source tree. The end result is that I get build failures such as this when I try to build from a source tree created by get-orig-source:
ninja: error: '../../third_party/breakpad/breakpad/src/common/convert_UTF.c', needed by 'obj/third_party/breakpad/client/convert_UTF.o', missing and no known rule to make it

And why does this occur? It occurs because the copyright file's excluded files includes wildcard patterns which are honored by the get-orig-source but not by setup-local-src so setup-local-src has the required files but get-orig-source does not. I traced this back to a difference in how debian/scripts/remove_copyright_excluded works. Apparently it ignores wildcard file patterns.

What can be done resolve this inconsistency? Thanks.

**Comment by ghost** [comment]
I think I found something. Apparently the remove_copyright_excluded script is only processing directories and never regular files and as such the file wildcard patterns will never match.

**Comment by Eloston** [comment]
> I think I found something. Apparently the remove_copyright_excluded script is only processing directories and never regular files and as such the file wildcard patterns will never match.

The wildcard paths should be processed in the loop denoted by `# Gather all paths that match wildcards`. The logic is a little convoluted because I made a small optimization: the recursive glob will explore directories before the files inside of them, so the loop will skip the children of directories that match a wildcard pattern. I remove both files and directories in `_remove_files()`

Can you give me some examples of paths that don't get matched correctly? I tried `third_party/breakpad/breakpad/src/common/convert_UTF.c`, and the filepath matching logic works correctly.

**Comment by ghost** [comment]
I'll retry this from a Debian 10 container, but I was finding that my builds were breaking because of some apparent difference in which files were kept or removed from the two methods of building a source tree. I was using Debian 10 to bootstrap the build for a Ubuntu Bionic PPA since I can't run get-orig-source successfully from a Bionic container as its packages are too old to have the newer mk-origtargz perl modules.

**Comment by ghost** [comment]
Ok. Tests complete on the ubuntu bionic branch at its latest tag. Here are my findings:

The local source tree created by setup-local-src has the path third_party/breakpad/breakpad/src/common/convert_UTF.c present even though the copyright file has it listed in its Files-Excluded list via a wildcard pattern.

The distribution tarball created by get-orig-source does not have the path third_party/breakpad/breakpad/src/common/convert_UTF.c because it is listed in the copyright file in its Files-Excluded list via a wildcard pattern.

So this is the issue I have noticed. I will retry it in the main debian branch just to see if it can be reproduced there. Frankly I only noticed this due to a build failure from the resulting tarball when I uploaded it to a PPA.

**Comment by ghost** [comment]
@Eloston, while I was waiting on this Debian 10 test to finish, I was reviewing the script again. I guess I don't know why it is happening but in my experiments with setup-local-src I observe some of the Files-Excluded wildcard patterns are still matching files after the script has run. If the script was working correctly, shouldn't these patterns fail to resolve to a file path?

These are the ones I observe as failing to remove files:
`chrome/common/safe_browsing/rar_analyzer.*`
`third_party/flot/*.js`
`third_party/zlib/adler*`
`third_party/zlib/crc32*`
`third_party/zlib/deflate*`
`third_party/zlib/gzguts*`
`third_party/zlib/in*`
`third_party/zlib/trees*`
`third_party/zlib/x86*`
`third_party/zlib/z*`
`third_party/ffmpeg/config*`
`third_party/google_input_tools/src/chrome/os/inputview/_locales/*.js` `third_party/breakpad/breakpad/src/common/convert_UTF.*`

**Comment by ghost** [comment]
Ok, Debian 10 test is complete. Same outcome as the Bionic test I did above. I'm not sure what should be done here to resolve this difference but it's apparent that the build process is currently dependent on the seemingly incorrect behavior of the remove_copyright_excluded script. Evidently the fact that it is not removing certain files has allowed setup-local-src to silently allow builds to continue working.

**Comment by ghost** [comment]
I will have to workaround this issue for my PPA via a custom method of creating the tarball I require. Still I think this needs to be resolved in some manner, but I'm not sure how because I am not very familiar with chromium's overly complex build system.

**Comment by Eloston** [comment]
Alright, I fixed the script to properly handle files now using `os.walk()`. Apparently `glob('**')` didn't traverse files, but `rglob('*')` will. However, I found that `os.walk()` will also handle dot files (i.e. files prefixed with `.`) and can skip traversing directories, thus its use in my implementation.

I also removed the `convert_UTF` exclusion. If you encounter any other exclusion issues, please let me know so I can remove them (or better, submit a PR).

**Comment by ghost** [comment]
Ok. I'll try doing a new build in awhile to see if there's any other missing files that break the build.
