### ISSUE TITLE
Use of Launchpad Personal Package Archives (PPAs)

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#51]
It would probably be a good idea to have an official system for automated builds. Given that, this is one of the available options but it comes with some limitations.

1. It is only available to Ubuntu derivations.
2. It can only use packages from official repositories or an existing PPA.
3. It has an initial limit of 2GB for source and binary packages combined.

To setup a PPA and build packages, you essentially have to do these steps:
1. Create a Launchpad account
2. Create a new GPG key capable of signing and verifying packages
3. Upload the public key to the [Ubuntu keyserver](https://keyserver.ubuntu.com)
4. Wait for the key to propagate
5. Add the key to the Lauchpad account created in step 1
6. Complete the verification process for the key addition
7. Create a new PPA
8. Configure the PPA settings; I would advise disabling builds for i386 at the very least.
9. Create a source package to upload; ensure it is signed with the GPG key you created earlier.
10. Upload the source package via dput. E.g., dput ppa:user/repo package.changes

Now how could this be done automatically? Most of the setup work is manual but the uploading of packages can be done automatically after that. To do so it would need access to a signing key associated with the account of the PPA. The rest is just a matter of scripting a series of commands that generate a source package to push out via dput.

**Comment by ghost** [comment]
@Eloston, I'm already planning to maintain my own PPA since Ubuntu decided to drop chromium as a regular package. I am also including some extra packages for easier updates to extensions I use regularly because automatic updates no longer function due to all the ungoogling effort so I figure the next best thing is to use the package manager to update them.

If this is something you would be interested in sponsoring then I wouldn't mind expanding it to include all of your Ubuntu packages though I am primarily interested in the LTS releases.

**Comment by Eloston** [comment]
> If this is something you would be interested in sponsoring then I wouldn't mind expanding it to include all of your Ubuntu packages though I am primarily interested in the LTS releases.

Any PPA is better than what we have right now, but I'm not interested in providing monetary support.

**Comment by ghost** [comment]
Ah, that's not what I meant. I was talking along the lines of an affiliation so maybe it could be considered an official source of binaries.

**Comment by Eloston** [comment]
Oh I see, yeah I'd be fine with that.

**Comment by ghost** [comment]
For now I'm working on updating the eoan and bionic branches to my recent changes to buster. This is so they can be ready to be built for the PPA, at least in theory.

**Comment by ghost** [comment]
That's done. Now I'll begin test builds of both in my new PPA. If it's successful then I'll give you the URL.

**Comment by ghost** [comment]
The builds I sent out for arm64 have failed due to a missing include so it looks like I will need to patch for these. How should I include a patch for minor build problems? Any preferences?

**Comment by Eloston** [comment]
Well since we just tagged a version for `79.0.3945.117-1`, we could add the patch and then increment the distro revision number in `debian/distro_revision.txt`. It's a little tedious, but it ensures we are clear about what changes we are including in our builds (so others can reproduce without issue).

For testing purposes, it might be easier to increment the distro revision first, then keep committing changes until it works, then we can tag it.

**Comment by ghost** [comment]
Ok. Well, for now, give me some time. I need to ensure that it successfully builds before I submit a final patch. Honestly this only appears to be a problem for arm64 so we don't need to increment it if you don't want to at this point in time. How many users actually would use this architecture?

**Comment by Eloston** [comment]
> Honestly this only appears to be a problem for arm64 so we don't need to increment it if you don't want to at this point in time. How many users actually would use this architecture?

In that case, we can just commit the patch but not have a corresponding tag until the next version comes out (i.e. Chromium updates or we add some feature).

**Comment by ghost** [comment]
It's odd though. armhf just failed as well for the same problem. amd64 has no issues here. I guess it's because the implicit includes are different and therefore it fails for this place because it was not explicitly included.

**Comment by ghost** [comment]
I have resolved the issue and am working on making the first official builds of this PPA available. But sheesh the armhf and arm64 build servers are significantly slower than the amd64 ones. They take at least twice as long to finish.

**Comment by ghost** [comment]
Ok so I think I'm as prepared as I'll ever be for this. This is the PPA.

https://launchpad.net/~braewoods/+archive/ubuntu/ungoogled-chromium
