### ISSUE TITLE
Further refinement of source targets

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#52]
Since you fixed the bug with `remove_copyright_excluded`, I have been examining how close the resulting source code trees created by `setup-local-src` and `get-orig-source` are. They are nearly identical now and I am going to see if I can make them 100% identical.

If this is successful I think I can modify `get-orig-source` to replace the more expensive method of removing the copyright exclusions with `remove_copyright_excluded`. This would make the differences between the two much smaller which should reduce the incidence of bugs that are specific to one or the other and also make `get-orig-source` faster.

**Comment by ghost** [comment]
With a small patch to `setup-local-src`, the resulting source trees are now equivalent. As it stands at this point, `setup-local-src` takes about 236 seconds and `get-dist-source` takes about 2594 seconds. I will see where my optimization efforts take me.

**Comment by ghost** [comment]
Ok, so my optimization results in `get-dist-source` taking about 1403 seconds. I'll try to clean it up some before I commit it.

**Comment by ghost** [comment]
And done. That should be the last of the changes I expect to make for now.

**Comment by Eloston** [comment]
Cool, thanks for fixing this up! I'm guessing the instructions in "Building via source package" should be updated too, e.g. specifying the uploader?

**Comment by ghost** [comment]
Yes, that should probably be specified but it's an optional step for most people. It's mainly relevant for uploading to a package building service. I will see about updating the documentation.

**Comment by ghost** [comment]
Ok, done. See #53. Side note, do you intend to continue updating the Bionic branch? Upstream officially supports it for 3 years on Desktop while some of the other derivatives like Linux Mint support it for the full 5 years. I can see about updating that once my documentation changes are accepted.

**Comment by ghost** [comment]
Since the related pull request was accepted I will close this issue.
