### ISSUE TITLE
compile error: TabStripModelChange

### ISSUE THREAD

**Issue by zaza42** [ungoogled-software/ungoogled-chromium-debian#7]
```
In file included from gen/chrome/browser/ui/ui_jumbo_33.cc:6:
./../../chrome/browser/ui/tabs/tab_strip_model_observer.cc:51:22: error: default
ing this default constructor would delete it after its first declaration
TabStripModelChange::TabStripModelChange() = default;
                     ^                              
../../chrome/browser/ui/tabs/tab_strip_model_observer.h:106:28: note: default constructor of 'TabStripModelChange' is implicitly deleted because field 'deltas_' of const-qualified type 'const std::vector<Delta>' would not be initialized
  const std::vector<Delta> deltas_;
                           ^
1 error generated.
[17609/20479] CXX obj/chrome/browser/ui/ui/ui_jumbo_99.o
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:140: override_dh_auto_build-arch] Error 1
make[1]: Leaving directory '/usr/src/sources/2019/browser/ung73/build/src'
make: *** [debian/rules:114: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

**Comment by Eloston** [comment]
I just took myself on a crash course on default constructors, and I still have no clue why this is happening. It doesn't help that the code the those files haven't changed at all since 72, and there's no other code in ungoogled-chromium that touches anything closely related.

What's your LLVM toolchain version?

**Comment by zaza42** [comment]
```
clang-8 -v
clang version 8.0.0-3 (tags/RELEASE_800/final)
Target: x86_64-pc-linux-gnu
```
Default package from Debian Sid: 1:8-3
https://packages.debian.org/source/sid/llvm-toolchain-8

**Comment by Eloston** [comment]
Interesting. I used LLVM from apt.llvm.org and I'm using the build right now. Could you try using LLVM from there, or building a newer version? (The one in apt.llvm.org is 8.0.1 revision 357234)

**Comment by zaza42** [comment]
The same. :-<
```
In file included from gen/chrome/browser/ui/ui_jumbo_33.cc:6:
./../../chrome/browser/ui/tabs/tab_strip_model_observer.cc:51:22: error: defaulting this default constructor would delete it after its first declaration
TabStripModelChange::TabStripModelChange() = default;
                     ^
../../chrome/browser/ui/tabs/tab_strip_model_observer.h:106:28: note: default constructor of 'TabStripModelChange' is implicitly deleted because field 'deltas_' of const-qualified type 'const std::vector<Delta>' would not be initialized
  const std::vector<Delta> deltas_;
                           ^
1 error generated.
[17735/20479] CXX obj/chrome/browser/ui/ui/ui_jumbo_47.o
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:140: override_dh_auto_build-arch] Error 1
make[1]: Leaving directory '/usr/src/sources/2019/browser/ung73/build/src'
make: *** [debian/rules:114: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```
```
$ clang-8  -v
clang version 8.0.1-svn357234-1~exp1~20190407125346.58 (branches/release_80)
Target: x86_64-pc-linux-gnu

```
Any other tip about another software version?
`gcc version 9.0.1 20190402 (experimental) [trunk revision 270074] (Debian 9-20190402-1) 
`

**Comment by zaza42** [comment]
I've set up a clean debian buster chroot with debootstrap, then ungoogled-chromium-l10n_73.0.3683.103 was compiled clearly. May some newer package caused the problem which are from sid/experimental.
I'm going to find out which package caused the error.

**Comment by kuboosoft** [comment]
@zaza42 Hi. Do you find the problem?

**Comment by FireBurn** [comment]
Hi

Changing:

../../chrome/browser/ui/tabs/tab_strip_model_observer.h:106:28: note: default constructor of 'TabStripModelChange' is implicitly deleted because field 'deltas_' of const-qualified type 'const std::vector<Delta>' would not be initialized
  const std::vector<Delta> deltas_;

to:

std::vector<Delta> deltas_;

fixes things for me on Gentoo

**Comment by kuboosoft** [comment]
@FireBurn nop; it doesn't solve the issue :crying_cat_face:

**Comment by BinaryKhaos** [comment]
Have a look [here](https://bugs.gentoo.org/686982). Basically the problem comes from using libstdc++-6.0.26 (gcc-9) with clang. I haven't had the time to fully investigate this, unfortunately. Hope it helps nevertheless.

**Comment by Eloston** [comment]
Closing since 78 is out. Let me know if this is still a problem.
