### ISSUE TITLE
Upgrading to 80.x

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#76]
It seems upstream still hasn't pushed any revisions to their chromium repository so I think I will try exploring the upgrade myself. Either way we may want to track the progress here.

**Comment by ghost** [comment]
I can't finish this. I don't have time to deal with whatever upstream choose to do. So let's wait for that I guess. Though here are some basic findings:

Jumbo will have to be removed.
`fixes/implicit-headers.patch` was applied upstream so it can be removed.
`fixes/naming-collision.patch` was applied upstream so it can be removed.

For some reason I was getting errors from ninja about missing files under the gen/ directory of the source root directory depending on other missing files and I could not get it to build beyond that. I don't know chromium well enough to even begin to know where to look for a solution to this.

**Comment by ghost** [comment]
Ok, seems chromium 80 has landed in Sid but there's still nothing about it in their package repository. Any suggestions how we should proceed? @Eloston

**Comment by berkley4** [comment]
If it's any help, the debian directory can be downloaded via https://deb.debian.org/debian/pool/main/c/chromium/chromium_80.0.3987.106-1.debian.tar.xz

**Comment by ghost** [comment]
I'm aware but it would probably be better to wait for the upstream git to be updated first so we can have proper history updates.

**Comment by ghost** [comment]
It's finally landed. I will try to make this work shortly.

**Comment by ghost** [comment]
Resolved by merging to debian_sid branch.
