### ISSUE TITLE
VA-API VP9 decoding not working (video is black and won't play)

### ISSUE THREAD

**Issue by Eloston** [ungoogled-software/ungoogled-chromium-debian#9]
Version: 73.0.3683.103-1.buster1

VA-API VP9 decoding does not seem to be working under X11. A black area appears where the video should be shown, and it won't play. No errors are printed out to stdout/stderr.

Here's a test site: https://base-n.de/webm/VP9%20Sample.html
YouTube videos also have the same problem.

The workaround is to disable `chrome://flags/#disable-accelerated-video-decode` so that software rendering is used.

Wayland works, but I don't think hardware acceleration is being used because it logs an error from `vaapi_wrapper.cc` that `vaInitialize failed: unknown libva error`.

Hardware: Intel HD 620 and UHD 630

@riyad Do you have this issue in your Ubuntu Cosmic build?

@xsmile Does VA-API acceleration work for you under Arch Linux?

**Comment by xsmile** [comment]
No issues here with an Intel HD 4000, however it doesn't accelerate VP9 decoding.

I found similar reports for Arch Linux and Fedora:
https://aur.archlinux.org/packages/chromium-vaapi/
https://bugzilla.redhat.com/show_bug.cgi?id=1694651

It might be better to reintroduce the old behavior and keep VA-API available, but disabled by default.

**Comment by riyad** [comment]
Tested on Ubuntu 18.10 (cosmic) with Intel HD 620 integrated graphics. 

-  In a Gnome-Wayland session both videos work.
- In a Gnome X11 session the VP8 video works, but the VP9 video is broken as described above. Disabling the "Hardware-accelerated video decode" flag indeed makes it work again.

**Comment by Eloston** [comment]
@riyad Thanks for testing.

@xsmile
> It might be better to reintroduce the old behavior and keep VA-API available, but disabled by default.

Could you clarify what you mean by "old behavior"?

**Comment by xsmile** [comment]
@Eloston The current patch [1] enables hardware acceleration by default, whereas the previous variant [2] - which isn't compatible to the current Chromium version anymore - requires users to explicitly enable several flags first.

1: https://salsa.debian.org/chromium-team/chromium/blob/master/debian/patches/fixes/vaapi.patch
2: https://chromium-review.googlesource.com/c/chromium/src/+/532294

**Comment by Eloston** [comment]
@xsmile I see. In that case, we can just set `chrome://flags/#disable-accelerated-video-decode` to be ~enabled~ disabled by default. Once VP9 decoding is fixed, we can ~disable~ enable it by default again.

**Comment by riyad** [comment]
I just tested a prebuild of mine on Ubuntu 19.04 (disco):

- In a Gnome-Wayland session both videos work with both settings.
- In a Gnome X11 session **disabling** the "Hardware-accelerated video decode" breaks the VP9 video. When enabled both videos play fine. :upside_down_face:

**Comment by Eloston** [comment]
I decided not to implement a fix for this issue in 74 since a good solution would be more involved than I thought it would be, and I'm hoping Debian will come up with a fix for this. Instead, please just set `chrome://flags/#disable-accelerated-video-decode` to Disabled manually.
