### ISSUE TITLE
Error message when loading JSON file for extension

### ISSUE THREAD

**Issue by TotalCaesar659** [ungoogled-software/ungoogled-chromium-debian#95]
When I create JSON file in /usr/share/chromium/extensions/ as said [here](https://ungoogled-software.github.io/ungoogled-chromium-wiki/faq#installing-the-crx-file) (External Extension Descriptor), browser from [PPA](https://launchpad.net/~braewoods/+archive/ubuntu/ungoogled-chromium) says "Failed to load extension from: /usr/share/chromium/extensions/[extension-id].json. Manifest file is missing or unreadable", but the browser loads the extension normally. @braewoods, could you check it? When I use [portable build](https://ungoogled-software.github.io/ungoogled-chromium-binaries/releases/linux_portable/64bit/80.0.3987.106-1.1), it's alright.

**Comment by ghost** [comment]
The Debian version is based on the upstream package which was designed to only work with unpacked extensions. CRX files are not an unpacked extension. Best advice I can give is to unpack it to a directory as that is what it is expecting to find.

**Comment by TotalCaesar659** [comment]
I've done more tests. This method with CRX works alright, it just needs to be polished. The only problem is splash windows with error message, it's annoying to skip 20+ windows for all extensions.
Is it possible to fix this? Maybe even with separate flag (--load-crx-extensions or smth like this).

**Comment by ghost** [comment]
Chromium 88 is now in progress. Reopen if this remains an issue.

**Comment by TotalCaesar659** [comment]
The issue is not resolved in 89.0.4389.114, so it has to be reopened.
